// ============================================================
//  Aquarium Cafe & Resturant — Waiter dictionary (EN + AR)
//  Delivery dispatch board: columns, cards, dispatch panel,
//  toasts, confirm dialogs — every string, both languages.
// ============================================================

export const dictionary = {
  en: {
    'app.tag': 'WAITER',
    'top.live': 'Live',
    'top.offline': 'Offline',
    'top.sound': 'Toggle notification sound',
    'top.notifications': 'Enable push notifications',
    'top.refresh': 'Refresh orders',
    'top.lang': 'التبديل إلى العربية',
    'top.clock': 'Current time',

    'meta.line': '{active} active · {today} today · updated {t}',

    'col.Received': 'Received',
    'col.Accepted': 'Accepted',
    'col.Preparing': 'Preparing',
    'col.Ready': 'Ready',
    'col.Out for Delivery': 'On the way',
    'col.Finished': 'Done',

    'empty.title': 'Nothing here',
    'empty.Received': 'Online delivery orders land here.',
    'empty.Accepted': 'Accepted orders wait for the kitchen here.',
    'empty.Preparing': 'Nothing on the stove for delivery.',
    'empty.Ready': 'Packed orders wait for a driver here.',
    'empty.Out for Delivery': 'No couriers on the road right now.',
    'empty.Finished': 'Completed & cancelled deliveries collect here.',

    'card.subtotal': 'Subtotal',
    'card.fee': 'Delivery',
    'card.discount': 'Discount',
    'card.points': 'Points',
    'card.total': 'Total',
    'card.free': 'Free',
    'card.eta': '~{n} min',
    'card.map': 'Map ↗',
    'card.mapTitle': 'Open in Google Maps',
    'card.callDriver': 'Call driver',
    'card.temp': 'Temp driver',
    'card.member': 'Member',
    'card.ptsUsed': '{n} pts used',
    'card.call': 'Call',

    'act.Accept': 'Accept',
    'act.Start Preparing': 'Start Preparing',
    'act.Mark Ready': 'Mark Ready',
    'act.Mark Delivered': 'Mark Delivered',
    'act.dispatch': 'Dispatch',
    'act.saving': 'Saving…',
    'act.reject': 'Reject',
    'act.cancel': 'Cancel',

    'dsp.driver': 'Driver',
    'dsp.permanent': 'Saved driver',
    'dsp.temp': 'Temporary',
    'dsp.choose': '— choose a driver —',
    'dsp.tempName': 'Temp driver name',
    'dsp.tempNamePh': 'e.g. Ahmed Samy',
    'dsp.tempPhone': 'Temp driver phone',
    'dsp.tempPhonePh': '+20 10…',
    'dsp.eta': 'ETA (min)',
    'dsp.note': 'Note',
    'dsp.notePh': 'e.g. call on arrival',
    'dsp.needDriver': 'Pick a driver before dispatching.',
    'dsp.needTempName': 'Enter the temporary driver name (2+ letters).',
    'dsp.needTempPhone': 'Enter a valid temporary driver phone.',
    'dsp.tempHint': 'Temporary: saved on this order only · customer can call him',

    'cf.reject': 'Reject delivery order {id} for {name}?',
    'cf.cancel': 'Cancel delivery order {id} for {name}?',

    'toast.new': 'New delivery order {id} — {name} · {total}',
    'toast.accepted': 'Order {id} accepted ✓',
    'toast.preparing': 'Order {id} is on the stove',
    'toast.ready': 'Order {id} is packed & ready',
    'toast.out': 'Order {id} is on its way 🛵',
    'toast.delivered': 'Order {id} delivered — nice one!',
    'toast.cancelled': 'Order {id} cancelled',
    'toast.moved': 'Order {id} → {status}',
    'toast.soundOn': 'Notification sound on',
    'toast.soundOff': 'Notification sound muted',
    'toast.notificationsOn': 'Browser notifications enabled',

    'pay.cash': 'Cash on delivery',
    'pay.card_on_delivery': 'Card on delivery',

    'time.justnow': 'just now',
    'time.min': '{m} min ago',
    'time.hm': '{h}h {m}m ago',

    'done.Delivered': 'Delivered',
    'done.Cancelled': 'Cancelled',
  },

  ar: {
    'app.tag': 'الويتر',
    'top.live': 'لايف',
    'top.offline': 'مفيش اتصال',
    'top.sound': 'شغّل/كمّم صوت التنبيه',
    'top.notifications': 'تفعيل إشعارات الطلبات',
    'top.refresh': 'حدّث الطلبات',
    'top.lang': 'Switch to English',
    'top.clock': 'الوقت الحالي',

    'meta.line': '{active} نشط · {today} النهارده · اتحدّث {t}',

    'col.Received': 'طلبات جديدة',
    'col.Accepted': 'مقبولة',
    'col.Preparing': 'بيتحضّر',
    'col.Ready': 'جاهز للتسليم',
    'col.Out for Delivery': 'في الطريق',
    'col.Finished': 'خلصان',

    'empty.title': 'مفيش حاجة هنا',
    'empty.Received': 'طلبات الدليفري الأونلاين بتوصل هنا.',
    'empty.Accepted': 'الطلبات المقبولة بتستنى المطبخ هنا.',
    'empty.Preparing': 'مفيش حاجة على النار دلوقتي.',
    'empty.Ready': 'الطلبات المتجهزة بتستنى كابتن هنا.',
    'empty.Out for Delivery': 'مفيش كباتن في الطريق دلوقتي.',
    'empty.Finished': 'الطلبات المكتملة والملغية بتتجمع هنا.',

    'card.subtotal': 'المجموع الفرعي',
    'card.fee': 'التوصيل',
    'card.discount': 'الخصم',
    'card.points': 'النقاط',
    'card.total': 'الإجمالي',
    'card.free': 'مجاني',
    'card.eta': '~{n} دقيقة',
    'card.map': 'خريطة ↗',
    'card.mapTitle': 'افتح في جوجل مابس',
    'card.callDriver': 'كلم الكابتن',
    'card.temp': 'كابتن مؤقت',
    'card.member': 'عضو',
    'card.ptsUsed': '{n} نقطة مستخدمة',
    'card.call': 'اتصال',

    'act.Accept': 'اقبل',
    'act.Start Preparing': 'ابدأ التجهيز',
    'act.Mark Ready': 'جاهز للتسليم',
    'act.Mark Delivered': 'تم التوصيل',
    'act.dispatch': 'ابعته',
    'act.saving': 'بنحفظ…',
    'act.reject': 'ارفض',
    'act.cancel': 'إلغاء',

    'dsp.driver': 'الكابتن',
    'dsp.permanent': 'كابتن مسجل',
    'dsp.temp': 'مؤقت',
    'dsp.choose': '— اختار كابتن —',
    'dsp.tempName': 'اسم الكابتن المؤقت',
    'dsp.tempNamePh': 'مثال: أحمد سامي',
    'dsp.tempPhone': 'موبايل الكابتن المؤقت',
    'dsp.tempPhonePh': '+20 10…',
    'dsp.eta': 'المدة (دقيقة)',
    'dsp.note': 'ملاحظة',
    'dsp.notePh': 'مثال: كلم العميل عند الوصول',
    'dsp.needDriver': 'اختار كابتن قبل ما تبعت الطلب.',
    'dsp.needTempName': 'اكتب اسم الكابتن المؤقت (حرفين على الأقل).',
    'dsp.needTempPhone': 'اكتب رقم موبايل صح للكابتن المؤقت.',
    'dsp.tempHint': 'مؤقت: بيتحفظ مع الطلب ده بس · العميل يقدر يكلمه',

    'cf.reject': 'ترفض طلب الدليفري {id} بتاع {name}؟',
    'cf.cancel': 'تلغي طلب الدليفري {id} بتاع {name}؟',

    'toast.new': 'طلب دليفري جديد {id} — {name} · {total}',
    'toast.accepted': 'الطلب {id} اتقبل ✓',
    'toast.preparing': 'الطلب {id} على النار',
    'toast.ready': 'الطلب {id} متجهز وجاهز',
    'toast.out': 'الطلب {id} في الطريق 🛵',
    'toast.delivered': 'الطلب {id} اتوصّل — شغل جامد!',
    'toast.cancelled': 'الطلب {id} اتلغى',
    'toast.moved': 'الطلب {id} → {status}',
    'toast.soundOn': 'صوت التنبيه شغال',
    'toast.soundOff': 'صوت التنبيه مكتوم',
    'toast.notificationsOn': 'تم تفعيل إشعارات المتصفح',

    'pay.cash': 'كاش عند الاستلام',
    'pay.card_on_delivery': 'كارت عند الاستلام',

    'time.justnow': 'دلوقتي حالًا',
    'time.min': 'من {m} دقيقة',
    'time.hm': 'من {h} ساعة و {m} دقيقة',

    'done.Delivered': 'اتوصّل',
    'done.Cancelled': 'اتلغى',
  },
};
