// ============================================================
//  Aquarium Cafe & Resturant — Admin console dictionary (v5)
//  EN + AR for every page: Studio (overview, customizer,
//  content, media, sections), Menu & Delivery (menu manager,
//  zones, discounts), Marketing (banners, gallery, reviews,
//  socials) and Operations (deliveries, drivers, settings).
// ============================================================

export const dictionary = {
  en: {
    /* ---- shell ---- */
    'side.tag': 'ADMIN',
    'side.gStudio': 'Studio',
    'side.overview': 'Overview',
    'side.customizer': 'Customizer',
    'side.content': 'Content',
    'side.media': 'Media Library',
    'side.sections': 'Sections',
    'side.gMenu': 'Menu & Delivery',
    'side.menu': 'Menu Manager',
    'side.zones': 'Delivery Zones',
    'side.discounts': 'Discounts & Coupons',
    'side.gMarketing': 'Marketing',
    'side.banners': 'Banners',
    'side.gallery': 'Gallery',
    'side.reviews': 'Reviews',
    'side.socials': 'Social Links',
    'side.gOps': 'Operations',
    'side.deliveries': 'Deliveries',
    'side.drivers': 'Drivers',
    'side.settings': 'Settings',
    'side.gLive': 'Live sites',
    'side.customer': 'Customer site',
    'side.waiter': 'Waiter board',
    'side.foot': 'Aquarium · Platform v5',

    'top.menu': 'Open navigation',
    'top.lang': 'التبديل إلى العربية',
    'top.saved': 'All changes saved',
    'top.saving': 'Saving…',
    'top.saveFailed': 'Save failed',

    'pt.overview': 'Overview',
    'pt.customizer': 'Website Customizer',
    'pt.content': 'Website Content',
    'pt.media': 'Media Library',
    'pt.sections': 'Page Sections',
    'pt.menu': 'Menu Manager',
    'pt.zones': 'Delivery Zones',
    'pt.discounts': 'Discounts & Coupons',
    'pt.banners': 'Homepage Banners',
    'pt.gallery': 'Gallery',
    'pt.reviews': 'Reviews Moderation',
    'pt.socials': 'Social Links',
    'pt.deliveries': 'Deliveries Monitor',
    'pt.drivers': 'Delivery Drivers',
    'pt.settings': 'Settings',

    /* ---- order statuses ---- */
    'status.Received': 'Received',
    'status.Accepted': 'Accepted',
    'status.Preparing': 'Preparing',
    'status.Ready': 'Ready for delivery',
    'status.Out for Delivery': 'Out for delivery',
    'status.Delivered': 'Delivered',
    'status.Cancelled': 'Cancelled',

    /* ---- common actions ---- */
    'act.save': 'Save',
    'act.add': 'Add',
    'act.edit': 'Edit',
    'act.del': 'Delete',
    'act.cancel': 'Cancel',
    'act.close': 'Close',
    'act.reload': 'Reload',
    'cf.title': 'Are you sure?',
    'cf.yes': 'Delete',
    'cf.no': 'Cancel',
    'err.load': 'Something went wrong while loading.',

    /* ---- shared control strings ---- */
    'g.optional': 'optional',
    'g.moveUp': 'Move up',
    'g.moveDown': 'Move down',
    'g.remove': 'Remove',
    'g.noItems': 'No {what} yet — add your first one.',
    'g.addItem': 'Add item',
    'g.noImage': 'No image selected',
    'g.library': 'Library',
    'g.upload': 'Upload',
    'g.clear': 'Clear',
    'g.uploadedLib': 'Uploaded to the Media Library',
    'g.hexWarn': 'Use a full hex color like #0d7d9e',

    /* ---- sections page ---- */
    'sc.hd': 'Page structure & features',
    'sc.intro': 'Drag sections to reorder the customer page, flick a switch to hide one, and toggle whole features. Changes save instantly — no code, no deploy.',
    'sc.drag': 'Drag to reorder',
    'sc.showAria': 'Show {label}',
    'sc.visible': 'Visible',
    'sc.hidden': 'Hidden',
    'sc.nowVisible': '{label} is now visible',
    'sc.nowHidden': '{label} is now hidden',
    'sc.orderSaved': 'Section order saved',
    'sc.feats': 'Feature switches',
    'sc.featsSub': 'whole flows on/off',
    'sc.ordering': 'Online delivery ordering',
    'sc.orderingHint': 'Cart, checkout & the waiter dispatch board',
    'sc.delivery': 'Delivery module',
    'sc.deliveryHint': 'Zones, fees & live order tracking on the website',
    'sc.orderingName': 'Online ordering',
    'sc.deliveryName': 'Delivery module',
    'sc.on': '{name} enabled — live',
    'sc.off': '{name} disabled — live',

    /* ---- menu manager ---- */
    'mn.searchPh': 'Search products or categories…',
    'mn.count': '{c} categories · {p} products',
    'mn.addCategory': 'Add category',
    'mn.addProduct': 'Add product',
    'mn.note': 'The customer menu mirrors this exact order — categories top-to-bottom, products inside each one. Disabled items stay hidden.',
    'mn.products': '{n} products',
    'mn.catVisible': 'Show category on the website',
    'mn.availability': 'Show on the website',
    'mn.featured': 'Featured — shown by the “Featured” chip',
    'mn.moveTo': 'Move to another category',
    'mn.addHere': 'Add a product to this category',
    'mn.emptyAll': 'No categories yet — add your first category to start building the menu.',
    'mn.emptyCat': 'No products here yet — press ＋ in the header to add one.',
    'mn.noMatch': 'Nothing matches the search in this category.',
    'mn.delCatTitle': 'Delete “{name}”?',
    'mn.delCatText': 'The category is removed from the website. It has to be empty first — move or delete its products.',
    'mn.delCatYes': 'Delete category',
    'mn.catDeleted': 'Category “{name}” deleted',
    'mn.delProdTitle': 'Delete “{name}”?',
    'mn.delProdText': 'If the product appears in past orders it is archived (hidden) instead, protecting order history.',
    'mn.delProdYes': 'Delete product',
    'mn.prodDeleted': '“{name}” deleted',
    'mn.prodSaved': '“{name}” saved ✓',
    'mn.prodAdded': '“{name}” added to the menu',
    'mn.catSaved': 'Category “{name}” saved ✓',
    'mn.catAdded': 'Category “{name}” created',
    'mn.shown': '“{name}” is visible on the menu',
    'mn.hidden': '“{name}” hidden from the menu',
    'mn.catShown': '“{name}” is visible on the website',
    'mn.catHidden': '“{name}” hidden from the website',
    'mn.moved': '“{name}” moved to {cat}',
    'mn.featuredOn': '★ “{name}” is now featured',
    'mn.featuredOff': '“{name}” unfeatured',

    /* ---- product form ---- */
    'pf.add': 'Add product',
    'pf.edit': 'Edit product',
    'pf.nameEn': 'Name (English)',
    'pf.nameEnPh': 'e.g. Grilled Sea Bass',
    'pf.nameAr': 'Name (Arabic)',
    'pf.nameArPh': 'مثال: قاروص مشوي',
    'pf.category': 'Category',
    'pf.price': 'Price (EGP)',
    'pf.badge': 'Badge',
    'pf.badgeOpt': 'optional',
    'pf.badgePh': "e.g. Chef's pick",
    'pf.descEn': 'Description (English)',
    'pf.descPh': 'A short, delicious description…',
    'pf.descAr': 'Description (Arabic)',
    'pf.descArPh': 'وصف قصير يفتح النفس…',
    'pf.visible': 'Visible on the customer menu',
    'pf.featured': '★ Featured product (shown by the “Featured” chip)',
    'pf.save': 'Save product',
    'pf.dropTitle': 'Drop image here',
    'pf.dropSub': 'or click to browse · PNG/JPG/WebP/SVG up to 6 MB',
    'pf.dropAria': 'Upload product image',
    'pf.uploading': 'Uploading…',
    'pf.removeImg': 'Remove image',
    'pf.chooseLib': 'Choose from Media Library',

    /* ---- category form ---- */
    'cf2.add': 'Add category',
    'cf2.edit': 'Edit category',
    'cf2.nameEn': 'Name (English)',
    'cf2.nameEnPh': 'e.g. Seasonal Specials',
    'cf2.nameAr': 'Name (Arabic)',
    'cf2.nameArPh': 'مثال: عروض الموسم',
    'cf2.hint': 'The menu chip slug is generated automatically from the English name.',
    'cf2.save': 'Save category',

    /* ---- zones page ---- */
    'zn.add': 'Add zone',
    'zn.note': 'Customers pick a main zone, then a sub zone, then type their detailed address. The fee charged is ALWAYS the selected sub zone’s own fee (the zone fee applies when no sub zone is chosen) — “free above” gives free delivery over that subtotal.',
    'zn.count': '{z} zones · {s} sub zones',
    'zn.empty': 'No delivery zones yet — add the areas you deliver to.',
    'zn.nameEn': 'Zone name (English)',
    'zn.nameAr': 'Zone name (Arabic)',
    'zn.nameArPh': 'اسم المنطقة بالعربي',
    'zn.fee': 'Fee',
    'zn.feeHint': 'Delivery fee added to orders in this zone (EGP). 0 = free delivery.',
    'zn.free': 'Free ≥',
    'zn.freeHint': 'Subtotal that makes delivery free in this zone. 0 = use the global setting from Settings.',
    'zn.active': 'Deliver to this zone',
    'zn.subs': 'Sub zones ({n})',
    'zn.subEn': 'Sub zone (English)',
    'zn.subAr': 'Sub zone (Arabic)',
    'zn.subEnPh': 'English name',
    'zn.subArPh': 'الاسم بالعربي',
    'zn.subFee': 'Sub zone delivery fee (EGP)',
    'zn.subFeeHint': 'This sub zone’s own delivery fee — it replaces the zone fee for customers who pick it. 0 = free delivery.',
    'zn.feeBad': 'Fee must be a number between 0 and 10000.',
    'zn.subActive': 'Available to customers',
    'zn.addSub': 'Add sub zone',
    'zn.newSubEn': 'New sub zone (EN)…',
    'zn.newSubAr': 'منطقة فرعية جديدة (ع)…',
    'zn.subShort': 'Type the sub zone name first (2+ characters).',
    'zn.added': 'Zone created — rename it and set its fee',
    'zn.saved': 'Saved ✓',
    'zn.feeSaved': 'Delivery fee for “{name}” updated',
    'zn.on': '“{name}” is now deliverable',
    'zn.off': '“{name}” paused — hidden from customers',
    'zn.subAdded': 'Sub zone “{name}” added',
    'zn.deleted': 'Zone “{name}” deleted',
    'zn.subDeleted': 'Sub zone “{name}” deleted',
    'zn.delTitle': 'Delete zone “{name}”?',
    'zn.delText': 'Its {n} sub zones are deleted too. Past orders keep their saved prices.',
    'zn.delYes': 'Delete zone',
    'zn.delSubTitle': 'Delete sub zone “{name}”?',
    'zn.delSubText': 'Customers will no longer pick it at checkout. Past orders are untouched.',

    /* ---- discounts page ---- */
    'dc.add': 'Add discount',
    'dc.edit': 'Edit discount',
    'dc.note': 'Signup reward, coupon codes and automatic discounts (global / product / category) all live here — and are enforced inside the database.',
    'dc.f.all': 'All',
    'dc.f.signup': 'Signup',
    'dc.f.coupon': 'Coupons',
    'dc.f.product': 'Product',
    'dc.f.category': 'Category',
    'dc.f.global': 'Global',
    'dc.t.signup': 'Signup reward',
    'dc.t.coupon': 'Coupon',
    'dc.t.product': 'Product',
    'dc.t.category': 'Category',
    'dc.t.global': 'Global',
    'dc.h.signup': 'Auto-applied to registered customers on their first delivered order. One active signup discount at a time works best.',
    'dc.h.coupon': 'Customers type this code at checkout. Leave max uses empty for unlimited.',
    'dc.h.product': 'Auto-applied whenever the cart contains this product.',
    'dc.h.category': 'Auto-applied to items from this category in the cart.',
    'dc.h.global': 'Auto-applied to every order that reaches the minimum.',
    'dc.name': 'Discount name',
    'dc.namePh': 'e.g. Welcome 10%',
    'dc.type': 'Type',
    'dc.code': 'Coupon code',
    'dc.valueType': 'Value type',
    'dc.percent': 'Percent %',
    'dc.fixed': 'Fixed EGP',
    'dc.valuePercent': 'Percent value (1–100)',
    'dc.valueFixed': 'Amount (EGP)',
    'dc.minOrder': 'Min. order (EGP)',
    'dc.maxDiscount': 'Max discount (EGP)',
    'dc.targetProduct': 'Applies to product',
    'dc.targetCategory': 'Applies to category',
    'dc.noTargets': 'Nothing to choose yet',
    'dc.maxUses': 'Max uses',
    'dc.expiry': 'Expiry date',
    'dc.activeNow': 'Active',
    'dc.save': 'Save discount',
    'dc.paused': 'Paused',
    'dc.live': 'Live',
    'dc.expired': 'Expired',
    'dc.usedUp': 'Used up',
    'dc.minShort': 'min {v} EGP',
    'dc.capShort': 'cap {v} EGP',
    'dc.usesShort': '{u}/{m} used',
    'dc.usedN': '{n} used',
    'dc.until': 'until {d}',
    'dc.empty': 'No discounts yet — create a signup reward or your first coupon.',
    'dc.emptyFilter': 'No discounts in this group.',
    'dc.on': '“{name}” is live',
    'dc.off': '“{name}” paused',
    'dc.saved': '“{name}” saved ✓',
    'dc.added': '“{name}” created',
    'dc.deleted': '“{name}” deleted',
    'dc.delTitle': 'Delete “{name}”?',
    'dc.delText': 'Customers stop getting it immediately. Orders that used it keep their records.',

    /* ---- settings ---- */
    'set.delivery': 'Delivery',
    'set.dEnabled': 'Delivery enabled',
    'set.dEnabledHint': 'Off = checkout is paused on the website',
    'set.minOrder': 'Minimum order',
    'set.freeAbove': 'Free delivery above (global)',
    'set.eta': 'Estimated delivery time',
    'set.payNote': 'Payment methods the customer can choose at checkout:',
    'set.cash': 'Cash on delivery',
    'set.card': 'Credit card on delivery',
    'set.payOne': 'At least one payment method has to stay enabled.',
    'set.note': 'Delivery note (shown at checkout)',
    'set.enforced': 'Fees themselves are set per zone on the Delivery Zones page — the database enforces all of this at checkout.',
    'set.rewards': 'Loyalty Rewards',
    'set.rEnabled': 'Loyalty program enabled',
    'set.rPPO': 'Points earned per delivered order',
    'set.rBonus': 'Signup bonus points',
    'set.rValue': 'Value of 1 point (EGP) when redeeming',
    'set.rMin': 'Minimum points per redemption',
    'set.rMax': 'Maximum points per redemption',
    'set.rNote': 'Customers collect points on every delivered order and redeem them as a discount at checkout. Your “value of 1 point” decides whether buying with points is worth it — set 0 to disable redemption.',
    'set.notifications': 'Notifications',
    'set.nSound': 'New-order sound',
    'set.nSoundHint': 'Chime on the waiter board when an order lands',
    'set.nBrowser': 'Browser notifications',
    'set.nBrowserHint': 'System notification even when the tab is hidden',
    'set.todoTitle': 'Business TODO',
    'set.todoIntro': 'What public research could NOT confirm about Aquarium. Work through it and check items off:',
    'set.todoCount': '{d} of {t} done',
    'set.todoAllDone': 'All done 🎉',
    'set.todoDel': 'Remove item',
    'set.todoAdd': 'Add a new to-do, e.g. “Confirm Ramadan hours”…',
    'set.autosave': 'Settings save automatically — the website and RPCs read these exact values.',

    /* ---- overview ---- */
    'ov.deliveriesToday': 'Deliveries today',
    'ov.deliveriesTodaySub': 'orders placed since midnight',
    'ov.revenue': 'Revenue today',
    'ov.revenueSub': 'delivered orders only',
    'ov.activeDesc': 'Active orders',
    'ov.activeSub': 'need attention now',
    'ov.drivers': 'Active drivers',
    'ov.driversSub': 'ready to dispatch',
    'ov.zones': 'Delivery zones',
    'ov.zonesSub': 'enabled right now',
    'ov.coupons': 'Live discounts',
    'ov.couponsSub': 'signup · coupons · auto',
    'ov.members': 'Loyalty members',
    'ov.membersSub': 'registered customers',
    'ov.reviews': 'Reviews pending',
    'ov.reviewsSub': 'waiting for approval',
    'ov.products': 'Menu products',
    'ov.productsSub': 'visible / total',
    'ov.itemsN': '{n} items',
    'ov.recentEmpty': 'No delivery orders yet — share your ordering link!',
    'ov.quickTitle': 'Quick actions',
    'ov.quickSub': 'jump straight to work',
    'ov.qDesign': 'Design the site',
    'ov.qMenu': 'Manage the menu',
    'ov.qZones': 'Zones & fees',
    'ov.qCoupons': 'Discounts',
    'ov.qBanners': 'Homepage banners',
    'ov.qDrivers': 'Drivers',
    'ov.qSettings': 'Settings',
    'ov.qWaiter': 'Waiter board',
    'ov.recentTitle': 'Latest orders',
    'ov.recentSub': 'newest first',
    'ov.watch': 'Open the deliveries monitor',
    'ov.todoTitle': 'Business TODO',
    'ov.todoDone': '{d}/{t} done',
    'ov.todoOpen': 'open Settings',
    'ov.todoMore': '+{n} more — see Settings',
    'ov.todoEmpty': 'Everything is done — nice! 🎉',

    /* ---- deliveries monitor ---- */
    'dm.monitor': 'Live orders',
    'dm.monitorSub': 'read-only · statuses advance on the waiter board',
    'dm.searchPh': 'Search name, phone, address, zone…',
    'dm.f.all': 'All',
    'dm.f.active': 'Active',
    'dm.f.done': 'Finished',
    'dm.reload': 'Reload',
    'dm.reloaded': 'Refreshed ✓',
    'dm.th.order': 'Order',
    'dm.th.customer': 'Customer',
    'dm.th.destination': 'Destination',
    'dm.th.captain': 'Captain',
    'dm.th.pay': 'Payment',
    'dm.th.total': 'Total',
    'dm.th.status': 'Status',
    'dm.th.age': 'Age',
    'dm.cash': 'Cash',
    'dm.card': 'Card',
    'dm.temp': 'Temp',
    'dm.member': 'Registered member',
    'dm.feeLine': 'fee {v}',
    'dm.discountLine': 'disc −{v}',
    'dm.pointsLine': '{n} pts used',
    'dm.now': 'just now',
    'dm.mins': '{n} min ago',
    'dm.hours': '{n} h ago',
    'dm.noResults': 'No orders match this view.',
    'dm.loaded': 'Orders loaded',
    'dm.loadedSub': 'latest 200',
    'dm.active': 'Active now',
    'dm.activeSub': 'not finished yet',
    'dm.doneToday': 'Delivered today',
    'dm.doneTodaySub': 'since midnight',
    'dm.revenueToday': 'Revenue today',
    'dm.revenueTodaySub': 'delivered orders',
    'dm.items': 'Items',
    'dm.noItems': '—',
    'dm.summary': 'Summary',
    'dm.subtotal': 'Subtotal',
    'dm.discount': 'Discount',
    'dm.fee': 'Delivery fee',
    'dm.total': 'Total',
    'dm.eta': 'Estimated time',
    'dm.minUnit': 'min',
    'dm.pointsRedeemed': 'Loyalty points redeemed ({n} pts)',
    'dm.earnedOnDelivery': 'Points earned when delivered',
    'dm.maps': 'Open in Maps',

    /* ---- drivers ---- */
    'drv.addHd': 'Add a driver',
    'drv.addSub': 'name + phone is all it takes',
    'drv.name': 'Driver name',
    'drv.namePh': 'e.g. Ahmed Samy',
    'drv.phone': 'Phone',
    'drv.phonePh': 'e.g. +20 100 123 4567',
    'drv.notes': 'Notes',
    'drv.notesPh': 'e.g. scooter · evenings (optional)',
    'drv.add': 'Add driver',
    'drv.hint': 'Only active drivers show up on the waiter board when dispatching.',
    'drv.listHd': 'Driver roster',
    'drv.count': '{a} active of {n}',
    'drv.empty': 'No drivers yet — add your first delivery captain above.',
    'drv.errName': 'Type the driver name first (2+ characters).',
    'drv.errPhone': 'Type a valid phone number (8+ digits).',
    'drv.added': '{name} joined the roster 🛵',
    'drv.saved': '{name} updated ✓',
    'drv.deleted': '{name} removed from the roster',
    'drv.on': '{name} is active',
    'drv.off': '{name} deactivated',
    'drv.active': 'Available for dispatch',
    'drv.editName': 'Driver name:',
    'drv.editPhone': 'Phone number:',
    'drv.editNotes': 'Notes (optional):',
    'drv.delTitle': 'Remove {name}?',
    'drv.delText': 'Past deliveries keep their history. The driver simply stops being offered at dispatch.',
    'drv.delYes': 'Remove driver',
    'drv.note': 'Need a one-off courier? At “Ready for delivery” the waiter can attach a temporary driver to a single order — it never lands in this roster.',

    /* ---- content editor ---- */
    'ct.about': 'About section',
    'ct.title': 'Title',
    'ct.story': 'Story text',
    'ct.aboutImg': 'About image',
    'ct.aboutImgHint': 'Shown next to the story',
    'ct.contact': 'Contact',
    'ct.address': 'Address',
    'ct.email': 'Email',
    'ct.wa': 'WhatsApp link',
    'ct.maps': 'Google Maps URL',
    'ct.phones': 'Phone numbers',
    'ct.addPhone': 'Add phone number',
    'ct.phone': 'phone number',
    'ct.hours': 'Working hours',
    'ct.days': 'Days',
    'ct.daysPh': 'Saturday – Thursday',
    'ct.hoursLb': 'Hours',
    'ct.hoursPh': '8:00 AM – 12:00 AM',
    'ct.addHours': 'Add hours row',
    'ct.hoursRow': 'hours row',
    'ct.branches': 'Branches',
    'ct.branch': 'Branch',
    'ct.branchPh': 'El Dahar — Flagship',
    'ct.branchAddrPh': 'Sheraton Road…',
    'ct.branchPhonePh': '+20 …',
    'ct.addBranch': 'Add branch',
    'ct.branchOne': 'branch',
    'ct.socials': 'Social media',
    'ct.socialsNote': 'Social links live in their own table with ordering & visibility switches — manage them on the',
    'ct.socialsPage': 'Social Links page →',
    'ct.highlights': 'Highlights strip',
    'ct.addPhrase': 'Add phrase',
    'ct.phrase': 'phrase',
    'ct.highlightsHint': 'The scrolling ribbon between the hero and the menu.',
    'ct.footer': 'Footer',
    'ct.footerAbout': 'Footer about line',
    'ct.footerAboutHint': 'Used when the café description is empty',
    'ct.autosave': 'Content saves automatically as you type — the customer website updates itself within a second via Realtime.',
    'ct.editing': 'Editing…',

    /* ---- media library ---- */
    'md.copy': 'Copy image URL',
    'md.replace': 'Replace image',
    'md.delete': 'Delete image',
    'md.use': 'Use this image',
    'md.allFolders': 'All folders',
    'md.uploaded': '“{name}” uploaded to /{folder}',
    'md.copied': 'Image URL copied — paste it anywhere',
    'md.replaced': '“{name}” replaced — every place that uses it updates',
    'md.delTitle': 'Delete “{name}”?',
    'md.delText': 'The file is removed from storage. Products or sections already using its URL will fall back to a placeholder.',
    'md.deleted': '“{name}” deleted',
    'md.searchPh': 'Search images…',
    'md.folderPh': 'Folder name',
    'md.folderAria': 'Upload folder',
    'md.upload': 'Upload',
    'md.count': '{n} images',
    'md.count1': '1 image',
    'md.emptyMatch': 'No images match — try another folder or search.',
    'md.emptyLibrary': 'The library is empty — upload your first image.',
    'md.emptyPicker': 'No images here yet — upload one.',

    /* ---- banners ---- */
    'bn.formAdd': 'Add a banner',
    'bn.formEdit': 'Edit banner',
    'bn.formSub': 'promo strip on the homepage',
    'bn.title': 'Title',
    'bn.titlePh': 'e.g. Fresh seafood Fridays',
    'bn.subtitle': 'Subtitle',
    'bn.subtitlePh': 'e.g. Every Friday from 6 PM — while it lasts',
    'bn.image': 'Banner image',
    'bn.ctaText': 'Button text (optional)',
    'bn.ctaTextPh': 'e.g. See the menu',
    'bn.ctaLink': 'Button link (optional)',
    'bn.visible': 'Visible on the homepage',
    'bn.save': 'Save banner',
    'bn.add': 'Add banner',
    'bn.cancelEdit': 'Cancel editing',
    'bn.saved': 'Banner saved ✓',
    'bn.added': 'Banner added 📣',
    'bn.deleted': 'Banner deleted',
    'bn.allHd': 'All banners',
    'bn.allSub': 'first visible banner shows on the homepage',
    'bn.empty': 'No banners yet — the homepage promo strip is hidden until you add one.',
    'bn.note': 'Banners appear below the hero on the customer website. Add a beautiful photo from your Media Library for the best effect.',
    'bn.moveEarlier': 'Move earlier',
    'bn.moveLater': 'Move later',
    'bn.editAria': 'Edit banner',
    'bn.delAria': 'Delete banner',
    'bn.delTitle': 'Delete this banner?',
    'bn.delText': '“{title}” disappears from the homepage.',
    'bn.delYes': 'Delete banner',
    'bn.liveOn': 'Banner is live on the homepage',
    'bn.liveOff': 'Banner hidden',

    /* ---- gallery ---- */
    'gl.alt': 'Gallery photo',
    'gl.captionPh': 'Caption (optional)',
    'gl.caption': 'Caption',
    'gl.show': 'Show on website',
    'gl.moveEarlier': 'Move earlier',
    'gl.moveLater': 'Move later',
    'gl.delAria': 'Delete photo',
    'gl.counts': '{n} photos · {v} visible',
    'gl.counts1': '1 photo · {v} visible',
    'gl.empty': 'No photos yet — add the aquarium, the sea view, the fresh catch…',
    'gl.addHd': 'Add a photo',
    'gl.addSub': 'from the Media Library or straight from your device',
    'gl.photo': 'Photo',
    'gl.titlePh': 'e.g. Sunset over the Red Sea',
    'gl.add': 'Add to gallery',
    'gl.chooseFirst': 'Choose a photo first.',
    'gl.added': 'Photo added to the gallery 📸',
    'gl.delTitle': 'Delete this photo?',
    'gl.delTextT': '“{title}” leaves the public gallery.',
    'gl.delText': 'The photo leaves the public gallery.',
    'gl.delYes': 'Delete photo',
    'gl.removed': 'Photo removed',
    'gl.captionSaved': 'Caption saved',
    'gl.visibleOn': 'Photo is visible on the website',
    'gl.visibleOff': 'Photo hidden',
    'gl.note': 'Hidden photos stay here for later — only visible ones appear on the website, in this exact order.',

    /* ---- reviews moderation ---- */
    'rv2.approve': 'Approve & publish',
    'rv2.unpublish': 'Unpublish',
    'rv2.delete': 'Delete',
    'rv2.srcWebsite': 'Website',
    'rv2.srcDemo': 'Sample',
    'rv2.srcGoogle': 'Google',
    'rv2.srcManual': 'Manual',
    'rv2.stPending': 'Awaiting approval',
    'rv2.stPendingSub': 'invisible to customers',
    'rv2.stLive': 'Published',
    'rv2.stLiveSub': 'on the website',
    'rv2.stAvg': 'Average (published)',
    'rv2.stAvgSub': 'Google shows 4.2 ★',
    'rv2.pendingHd': 'Awaiting approval',
    'rv2.pendingSub': 'website reviews land here first',
    'rv2.liveHd': 'Published',
    'rv2.liveSub': 'visible on the customer website',
    'rv2.inboxZero': 'Inbox zero — nothing waiting for approval. 🌊',
    'rv2.noLive': 'No published reviews yet — approve one above, or wait for the first customer review.',
    'rv2.note': 'Customers submit reviews on the website — they never go live until you approve them here.',
    'rv2.live': 'Review by {name} is live ⭐',
    'rv2.unpublished': 'Review unpublished',
    'rv2.delTitle': 'Delete this review?',
    'rv2.cannotUndo': '— this cannot be undone.',
    'rv2.delYes': 'Delete review',
    'rv2.deleted': 'Review deleted',
    'rv2.guest': 'guest',

    /* ---- social links ---- */
    'so.choose': 'Choose platform…',
    'so.empty': 'No social links yet — add your Facebook page first, customers look for it.',
    'so.addHd': 'Add a link',
    'so.addSub': 'one per platform',
    'so.urlPh': 'https://www.facebook.com/yourpage',
    'so.add': 'Add link',
    'so.hint': 'Current official accounts are pre-filled — update them if ownership changes.',
    'so.allHd': 'All links',
    'so.allSub': 'shown in the footer & contact section, in this order',
    'so.chooseFirst': 'Choose a platform first.',
    'so.httpsWarn': 'Links should start with https://',
    'so.added': '{platform} link added 🔗',
    'so.delTitle': 'Delete the {platform} link?',
    'so.delText': 'It disappears from the website footer and the contact section.',
    'so.delYes': 'Delete link',
    'so.deleted': 'Link deleted',
    'so.saved': 'Link saved',
    'so.visibleOn': 'Link is visible on the website',
    'so.visibleOff': 'Link hidden',
    'so.show': 'Show on website',
    'so.moveUp': 'Move up',
    'so.moveDown': 'Move down',
    'so.delAria': 'Delete link',

    /* ---- customizer ---- */
    'cz.live': 'Live preview',
    'cz.deviceAria': 'Preview size',
    'cz.desktop': 'Desktop preview',
    'cz.mobile': 'Mobile preview',
    'cz.dirty': '● Unsaved',
    'cz.reload': 'Reload preview',
    'cz.openSite': 'Open site',
    'cz.reset': 'Reset',
    'cz.save': 'Save changes',
    'cz.saving': 'Saving…',
    'cz.savingState': 'Saving theme to Supabase…',
    'cz.unsavedState': 'Unsaved changes',
    'cz.savedState': 'All changes saved',
    'cz.savedToast': 'Design saved — live on the customer site ✦',
    'cz.discardTitle': 'Discard unsaved changes?',
    'cz.discardText': 'The panels and preview return to the last saved design.',
    'cz.discardYes': 'Discard',
    'cz.reverted': 'Reverted to the saved design',
    'cz.hint1': 'Every control repaints the preview instantly — nothing is published until you press',
    'cz.hint2': 'Open customer tabs then update automatically.',
    'cz.tabsAria': 'Customizer panels',
    'cz.frameTitle': 'Customer site live preview',
    'cz.g.identity': 'Café identity',
    'cz.cafeName': 'Cafe name',
    'cz.slogan': 'Slogan / tagline',
    'cz.description': 'Description',
    'cz.copyright': 'Copyright line',
    'cz.copyrightHint': 'Use {year} for the current year',
    'cz.g.logo': 'Logo & favicon',
    'cz.logo': 'Logo',
    'cz.logoHint': 'Shown in the navbar & footer',
    'cz.favicon': 'Favicon',
    'cz.faviconHint': 'Browser-tab icon (square looks best)',
    'cz.g.regional': 'Regional',
    'cz.currency': 'Currency label',
    'cz.g.palette': 'Brand palette',
    'cz.primary': 'Primary',
    'cz.secondary': 'Secondary',
    'cz.accent': 'Accent',
    'cz.g.surfaces': 'Surfaces',
    'cz.background': 'Background',
    'cz.sectionBg': 'Section background',
    'cz.cardBg': 'Card background',
    'cz.border': 'Border',
    'cz.g.btnText': 'Buttons & text',
    'cz.buttonBg': 'Button color',
    'cz.buttonHover': 'Button hover',
    'cz.text': 'Text',
    'cz.headings': 'Headings',
    'cz.g.chrome': 'Chrome',
    'cz.navbarBg': 'Navbar',
    'cz.footerBg': 'Footer',
    'cz.overlay': 'Modal overlay',
    'cz.g.fonts': 'Font families',
    'cz.headingFont': 'Heading font',
    'cz.bodyFont': 'Body font',
    'cz.g.sizes': 'Sizes & weight',
    'cz.bodySize': 'Body size',
    'cz.h1Size': 'Hero title (H1)',
    'cz.h2Size': 'Section title (H2)',
    'cz.h3Size': 'Card title (H3)',
    'cz.headingWeight': 'Heading weight',
    'cz.bodyWeight': 'Body weight',
    'cz.g.rhythm': 'Rhythm',
    'cz.letterSpacing': 'Letter spacing',
    'cz.lineHeight': 'Line height',
    'cz.g.canvas': 'Canvas',
    'cz.containerWidth': 'Container width',
    'cz.spacing': 'Grid gap / spacing',
    'cz.sectionPadding': 'Section padding',
    'cz.g.cards': 'Cards & depth',
    'cz.cardRadius': 'Card radius',
    'cz.shadowSize': 'Shadow size',
    'cz.gridColumns': 'Menu grid columns',
    'cz.g.heroBg': 'Hero backdrop',
    'cz.heroImage': 'Hero image',
    'cz.heroImageHint': 'A wide, moody sea shot works best',
    'cz.bgColor': 'Background color',
    'cz.overlayColor': 'Overlay color',
    'cz.overlayOpacity': 'Overlay darkness',
    'cz.g.heroCopy': 'Hero copy',
    'cz.heroTitle': 'Hero title',
    'cz.heroSubtitle': 'Hero subtitle',
    'cz.heroButton': 'Button text',
    'cz.heroLink': 'Button link',
    'cz.heroLinkHint': '#menu, #about… or a full URL',
    'cz.g.barBehavior': 'Bar behavior',
    'cz.navbarStyle': 'Navbar style',
    'cz.navGlass': 'Glass (blurred)',
    'cz.navSolid': 'Solid',
    'cz.navTransparent': 'Transparent over hero',
    'cz.sticky': 'Sticky',
    'cz.stickyHint': 'Stay pinned while scrolling',
    'cz.blur': 'Background blur',
    'cz.transparency': 'Background opacity',
    'cz.logoSize': 'Logo size',
    'cz.g.navItems': 'Navigation items',
    'cz.navLabel': 'Label',
    'cz.navLabelPh': 'Menu',
    'cz.navLink': 'Link',
    'cz.addNav': 'Add navigation link',
    'cz.navItemsHint': 'Anchor links (#menu, #about, #contact) scroll on-page; anything else opens in a new tab.',
    'cz.g.cardDesign': 'Card design',
    'cz.cardStyle': 'Card style',
    'cz.cardElevated': 'Elevated (shadow)',
    'cz.cardOutline': 'Outline',
    'cz.cardFlat': 'Flat / tinted',
    'cz.borderRadius': 'Border radius',
    'cz.shadow': 'Shadow',
    'cz.hoverAnim': 'Hover animation',
    'cz.innerPadding': 'Inner padding',
    'cz.g.cardImage': 'Card image',
    'cz.imageRatio': 'Image ratio',
    'cz.imageSize': 'Image size',
    'cz.g.btnDesign': 'Button design',
    'cz.style': 'Style',
    'cz.styleSolid': 'Solid',
    'cz.styleOutline': 'Outline',
    'cz.styleSoft': 'Soft (tinted)',
    'cz.size': 'Size',
    'cz.sizeS': 'Small',
    'cz.sizeM': 'Medium',
    'cz.sizeL': 'Large',
    'cz.animLift': 'Lift',
    'cz.animScale': 'Scale',
    'cz.animGlow': 'Glow ring',
    'cz.animNone': 'None',
    'cz.g.motion': 'Motion',
    'cz.animEnabled': 'Animations enabled',
    'cz.animEnabledHint': 'Off = instant, accessible rendering',
    'cz.revealType': 'Reveal type',
    'cz.revealRise': 'Rise (fade up)',
    'cz.revealFade': 'Fade',
    'cz.revealZoom': 'Zoom in',
    'cz.revealSlide': 'Slide sideways',
    'cz.baseDuration': 'Base duration',
    'cz.speed': 'Speed',
    'cz.t.general': 'General',
    'cz.t.colors': 'Colors',
    'cz.t.typography': 'Typography',
    'cz.t.layout': 'Layout',
    'cz.t.hero': 'Hero',
    'cz.t.navbar': 'Navbar',
    'cz.t.cards': 'Product Card',
    'cz.t.buttons': 'Buttons',
    'cz.t.animations': 'Animations',

    /* ---- misc controls ---- */
    'g.fontPreview': 'Aa — The quick brown fox 01234',
  },

  /* ════════════════════ ARABIC ════════════════════ */
  ar: {
    /* ---- shell ---- */
    'side.tag': 'الإدارة',
    'side.gStudio': 'الاستوديو',
    'side.overview': 'نظرة عامة',
    'side.customizer': 'تخصيص الموقع',
    'side.content': 'محتوى الموقع',
    'side.media': 'مكتبة الصور',
    'side.sections': 'أقسام الصفحة',
    'side.gMenu': 'المنيو والتوصيل',
    'side.menu': 'إدارة المنيو',
    'side.zones': 'مناطق التوصيل',
    'side.discounts': 'الخصومات والكوبونات',
    'side.gMarketing': 'التسويق',
    'side.banners': 'البانرات',
    'side.gallery': 'معرض الصور',
    'side.reviews': 'التقييمات',
    'side.socials': 'لينكات السوشيال',
    'side.gOps': 'التشغيل',
    'side.deliveries': 'التوصيل',
    'side.drivers': 'الكباتن',
    'side.settings': 'الإعدادات',
    'side.gLive': 'المواقع المباشرة',
    'side.customer': 'موقع العملاء',
    'side.waiter': 'لوحة الجارسون',
    'side.foot': 'أكواريوم · إصدار 5',

    'top.menu': 'افتح التنقل',
    'top.lang': 'Switch to English',
    'top.saved': 'كل التغييرات اتحفظت',
    'top.saving': 'بيتحفظ…',
    'top.saveFailed': 'الحفظ فشل',

    'pt.overview': 'نظرة عامة',
    'pt.customizer': 'تخصيص الموقع',
    'pt.content': 'محتوى الموقع',
    'pt.media': 'مكتبة الصور',
    'pt.sections': 'أقسام الصفحة',
    'pt.menu': 'إدارة المنيو',
    'pt.zones': 'مناطق التوصيل',
    'pt.discounts': 'الخصومات والكوبونات',
    'pt.banners': 'بانرات الصفحة الرئيسية',
    'pt.gallery': 'معرض الصور',
    'pt.reviews': 'مراجعة التقييمات',
    'pt.socials': 'لينكات السوشيال',
    'pt.deliveries': 'متابعة التوصيل',
    'pt.drivers': 'كباتن التوصيل',
    'pt.settings': 'الإعدادات',

    'status.Received': 'تم الاستلام',
    'status.Accepted': 'تم القبول',
    'status.Preparing': 'قيد التحضير',
    'status.Ready': 'جاهز للتوصيل',
    'status.Out for Delivery': 'خرج للتوصيل',
    'status.Delivered': 'تم التوصيل',
    'status.Cancelled': 'ملغي',

    'act.save': 'احفظ',
    'act.add': 'أضف',
    'act.edit': 'عدل',
    'act.del': 'امسح',
    'act.cancel': 'إلغاء',
    'act.close': 'اقفل',
    'act.reload': 'حدث',
    'cf.title': 'متأكد؟',
    'cf.yes': 'امسح',
    'cf.no': 'إلغاء',
    'err.load': 'حصلت مشكلة أثناء التحميل.',

    'g.optional': 'اختياري',
    'g.moveUp': 'اطلع فوق',
    'g.moveDown': 'انزل تحت',
    'g.remove': 'شيل',
    'g.noItems': 'مفيش {what} لسه — ضيف أول واحد.',
    'g.addItem': 'أضف عنصر',
    'g.noImage': 'لسه مفيش صورة مختارة',
    'g.library': 'المكتبة',
    'g.upload': 'ارفع',
    'g.clear': 'امسح',
    'g.uploadedLib': 'اترفعت لمكتبة الصور',
    'g.hexWarn': 'استخدم كود لون كامل زي #0d7d9e',

    'sc.hd': 'هيكل الصفحة والمزايا',
    'sc.intro': 'اسحب الأقسام عشان ترتب صفحة العملاء، اقلب المفتاح عشان تخفي قسم، وفعّل أو عطّل مزايا كاملة. التغييرات بتتحفظ فورًا — من غير كود ولا نشر.',
    'sc.drag': 'اسحب للترتيب',
    'sc.showAria': 'اظهر {label}',
    'sc.visible': 'ظاهر',
    'sc.hidden': 'مخفي',
    'sc.nowVisible': '{label} بقى ظاهر',
    'sc.nowHidden': '{label} بقى مخفي',
    'sc.orderSaved': 'ترتيب الأقسام اتحفظ',
    'sc.feats': 'مفاتيح المزايا',
    'sc.featsSub': 'تدفقات كاملة شغالة/مقفولة',
    'sc.ordering': 'طلبات التوصيل أونلاين',
    'sc.orderingHint': 'السلة واتمام الطلب ولوحة الجارسون',
    'sc.delivery': 'نظام التوصيل',
    'sc.deliveryHint': 'المناطق والرسوم وتتبع الطلب المباشر على الموقع',
    'sc.orderingName': 'الطلب أونلاين',
    'sc.deliveryName': 'نظام التوصيل',
    'sc.on': '{name} اتفعّل — مباشر',
    'sc.off': '{name} اتعطّل — مباشر',

    'mn.searchPh': 'دور في الأصناف أو الفئات…',
    'mn.count': '{c} فئات · {p} صنف',
    'mn.addCategory': 'أضف فئة',
    'mn.addProduct': 'أضف صنف',
    'mn.note': 'منيو العملاء بيطابق الترتيب ده بالظبط — الفئات من فوق لتحت، والأصناف جوه كل فئة. العناصر المعطّلة بتفضل مخفية.',
    'mn.products': '{n} صنف',
    'mn.catVisible': 'اظهر الفئة على الموقع',
    'mn.availability': 'اظهر على الموقع',
    'mn.featured': 'مميز — بيظهر مع فلتر «مميز»',
    'mn.moveTo': 'انقل لفئة تانية',
    'mn.addHere': 'ضيف صنف للفئة دي',
    'mn.emptyAll': 'مفيش فئات لسه — ضيف أول فئة عشان تبني المنيو.',
    'mn.emptyCat': 'مفيش أصناف هنا لسه — دوس ＋ فوق عشان تضيف.',
    'mn.noMatch': 'مفيش نتايج للبحث في الفئة دي.',
    'mn.delCatTitle': 'تحذف «{name}»؟',
    'mn.delCatText': 'الفئة بتتشال من الموقع. لازم تكون فاضية الأول — انقل أو امسح أصنافها.',
    'mn.delCatYes': 'امسح الفئة',
    'mn.catDeleted': 'الفئة «{name}» اتحذفت',
    'mn.delProdTitle': 'تحذف «{name}»؟',
    'mn.delProdText': 'لو الصنف موجود في طلبات قديمة بيتؤرشف (بيختفي) بدل المسح، حفاظًا على سجل الطلبات.',
    'mn.delProdYes': 'امسح الصنف',
    'mn.prodDeleted': '«{name}» اتحذف',
    'mn.prodSaved': '«{name}» اتحفظ ✓',
    'mn.prodAdded': '«{name}» اتضاف للمنيو',
    'mn.catSaved': 'الفئة «{name}» اتحفظت ✓',
    'mn.catAdded': 'الفئة «{name}» اتعملت',
    'mn.shown': '«{name}» بقى ظاهر في المنيو',
    'mn.hidden': '«{name}» اتخفى من المنيو',
    'mn.catShown': '«{name}» بقت ظاهرة على الموقع',
    'mn.catHidden': '«{name}» اتخفت من الموقع',
    'mn.moved': '«{name}» اتنقل لـ {cat}',
    'mn.featuredOn': '★ «{name}» بقى مميز',
    'mn.featuredOff': '«{name}» مش مميز دلوقتي',

    'pf.add': 'أضف صنف',
    'pf.edit': 'عدل الصنف',
    'pf.nameEn': 'الاسم (إنجليزي)',
    'pf.nameEnPh': 'مثال: Grilled Sea Bass',
    'pf.nameAr': 'الاسم (عربي)',
    'pf.nameArPh': 'مثال: قاروص مشوي',
    'pf.category': 'الفئة',
    'pf.price': 'السعر (جنيه)',
    'pf.badge': 'الشارة',
    'pf.badgeOpt': 'اختياري',
    'pf.badgePh': 'مثال: اختيار الشيف',
    'pf.descEn': 'الوصف (إنجليزي)',
    'pf.descPh': 'A short, delicious description…',
    'pf.descAr': 'الوصف (عربي)',
    'pf.descArPh': 'وصف قصير يفتح النفس…',
    'pf.visible': 'ظاهر في منيو العملاء',
    'pf.featured': '★ صنف مميز (بيظهر مع فلتر «مميز»)',
    'pf.save': 'احفظ الصنف',
    'pf.dropTitle': 'ارمي الصورة هنا',
    'pf.dropSub': 'أو دوس للاختيار · PNG/JPG/WebP/SVG لحد 6 ميجا',
    'pf.dropAria': 'ارفع صورة الصنف',
    'pf.uploading': 'بترفع…',
    'pf.removeImg': 'شيل الصورة',
    'pf.chooseLib': 'اختار من مكتبة الصور',

    'cf2.add': 'أضف فئة',
    'cf2.edit': 'عدل الفئة',
    'cf2.nameEn': 'الاسم (إنجليزي)',
    'cf2.nameEnPh': 'مثال: Seasonal Specials',
    'cf2.nameAr': 'الاسم (عربي)',
    'cf2.nameArPh': 'مثال: عروض الموسم',
    'cf2.hint': 'الفلتر بتاع المنيو بيتعمل تلقائيًا من الاسم الإنجليزي.',
    'cf2.save': 'احفظ الفئة',

    'zn.add': 'أضف منطقة',
    'zn.note': 'العميل بيختار المنطقة الرئيسية، بعدين المنطقة الفرعية، بعدين بيكتب عنوانه بالتفصيل. الرسوم اللي بتتحسب دايمًا هي رسوم المنطقة الفرعية المختارة (رسوم المنطقة الرئيسية بتتطبق لما مفيش منطقة فرعية تتختار) — و«مجاني فوق» بيدي توصيل مجاني فوق المبلغ ده.',
    'zn.count': '{z} مناطق · {s} مناطق فرعية',
    'zn.empty': 'مفيش مناطق توصيل لسه — ضيف المناطق اللي بتوصلوها.',
    'zn.nameEn': 'اسم المنطقة (إنجليزي)',
    'zn.nameAr': 'اسم المنطقة (عربي)',
    'zn.nameArPh': 'اسم المنطقة بالعربي',
    'zn.fee': 'الرسوم',
    'zn.feeHint': 'رسوم التوصيل اللي بتتضاف لطلبات المنطقة دي (جنيه). 0 = توصيل مجاني.',
    'zn.free': 'مجاني ≥',
    'zn.freeHint': 'قيمة الطلب اللي تخلي التوصيل مجاني في المنطقة دي. 0 = استخدم الإعداد العام من صفحة الإعدادات.',
    'zn.active': 'التوصيل متاح للمنطقة دي',
    'zn.subs': 'المناطق الفرعية ({n})',
    'zn.subEn': 'المنطقة الفرعية (إنجليزي)',
    'zn.subAr': 'المنطقة الفرعية (عربي)',
    'zn.subEnPh': 'الاسم بالإنجليزي',
    'zn.subArPh': 'الاسم بالعربي',
    'zn.subFee': 'رسوم توصيل المنطقة الفرعية (جنيه)',
    'zn.subFeeHint': 'رسوم التوصيل الخاصة بالمنطقة الفرعية دي — بتحل محل رسوم المنطقة الرئيسية للعملاء اللي بيختاروها. 0 = توصيل مجاني.',
    'zn.feeBad': 'الرسوم لازم تكون رقم بين 0 و 10000.',
    'zn.subActive': 'متاحة للعملاء',
    'zn.addSub': 'أضف منطقة فرعية',
    'zn.newSubEn': 'منطقة فرعية جديدة (EN)…',
    'zn.newSubAr': 'منطقة فرعية جديدة (ع)…',
    'zn.subShort': 'اكتب اسم المنطقة الفرعية الأول (حرفين على الأقل).',
    'zn.added': 'المنطقة اتعملت — غير اسمها وظبط رسومها',
    'zn.saved': 'اتحفظ ✓',
    'zn.feeSaved': 'رسوم توصيل «{name}» اتحدثت',
    'zn.on': '«{name}» بقت متاحة للتوصيل',
    'zn.off': '«{name}» متوقفة — مخفية عن العملاء',
    'zn.subAdded': 'المنطقة الفرعية «{name}» اتضافت',
    'zn.deleted': 'المنطقة «{name}» اتحذفت',
    'zn.subDeleted': 'المنطقة الفرعية «{name}» اتحذفت',
    'zn.delTitle': 'تحذف منطقة «{name}»؟',
    'zn.delText': 'مناطقها الفرعية ({n}) هيتحذفوا معاها. الطلبات القديمة بتحتفظ بأسعارها.',
    'zn.delYes': 'امسح المنطقة',
    'zn.delSubTitle': 'تحذف منطقة «{name}» الفرعية؟',
    'zn.delSubText': 'العملاء مش هيقدروا يختاروها عند الطلب. الطلبات القديمة زي ما هي.',

    'dc.add': 'أضف خصم',
    'dc.edit': 'عدل الخصم',
    'dc.note': 'مكافأة التسجيل وأكواد الكوبونات والخصومات التلقائية (عام / صنف / فئة) كلها هنا — وبتتطبق جوه قاعدة البيانات.',
    'dc.f.all': 'الكل',
    'dc.f.signup': 'التسجيل',
    'dc.f.coupon': 'كوبونات',
    'dc.f.product': 'صنف',
    'dc.f.category': 'فئة',
    'dc.f.global': 'عام',
    'dc.t.signup': 'مكافأة التسجيل',
    'dc.t.coupon': 'كوبون',
    'dc.t.product': 'صنف',
    'dc.t.category': 'فئة',
    'dc.t.global': 'عام',
    'dc.h.signup': 'بيتحسب تلقائيًا للعملاء المسجلين في أول طلب مكتمل. الأفضل خصم تسجيل واحد شغال في نفس الوقت.',
    'dc.h.coupon': 'العميل بيكتب الكود ده عند إتمام الطلب. سيب أقصى استخدام فاضي للا محدود.',
    'dc.h.product': 'بيتحسب تلقائيًا لما السلة تحتوي الصنف ده.',
    'dc.h.category': 'بيتحسب تلقائيًا على أصناف الفئة دي في السلة.',
    'dc.h.global': 'بيتحسب تلقائيًا على أي طلب يوصل للحد الأدنى.',
    'dc.name': 'اسم الخصم',
    'dc.namePh': 'مثال: خصم ترحيبي 10%',
    'dc.type': 'النوع',
    'dc.code': 'كود الكوبون',
    'dc.valueType': 'نوع القيمة',
    'dc.percent': 'نسبة %',
    'dc.fixed': 'مبلغ ثابت',
    'dc.valuePercent': 'النسبة (1–100)',
    'dc.valueFixed': 'المبلغ (جنيه)',
    'dc.minOrder': 'أقل قيمة طلب (جنيه)',
    'dc.maxDiscount': 'أقصى خصم (جنيه)',
    'dc.targetProduct': 'بيخصم على صنف',
    'dc.targetCategory': 'بيخصم على فئة',
    'dc.noTargets': 'مفيش حاجة للاختيار لسه',
    'dc.maxUses': 'أقصى استخدام',
    'dc.expiry': 'تاريخ الانتهاء',
    'dc.activeNow': 'شغال',
    'dc.save': 'احفظ الخصم',
    'dc.paused': 'متوقف',
    'dc.live': 'شغال',
    'dc.expired': 'منتهي',
    'dc.usedUp': 'خلصت عدته',
    'dc.minShort': 'أقل طلب {v} ج',
    'dc.capShort': 'بحد أقصى {v} ج',
    'dc.usesShort': '{u}/{m} استخدام',
    'dc.usedN': '{n} استخدام',
    'dc.until': 'لحد {d}',
    'dc.empty': 'مفيش خصومات لسه — اعمل مكافأة تسجيل أو أول كوبون.',
    'dc.emptyFilter': 'مفيش خصومات في المجموعة دي.',
    'dc.on': '«{name}» شغال دلوقتي',
    'dc.off': '«{name}» متوقف مؤقتًا',
    'dc.saved': '«{name}» اتحفظ ✓',
    'dc.added': '«{name}» اتعمل',
    'dc.deleted': '«{name}» اتحذف',
    'dc.delTitle': 'تحذف «{name}»؟',
    'dc.delText': 'العملاء هيبطلوا ياخدوه فورًا. الطلبات اللي استخدمته بتحتفظ بسجلاتها.',

    'set.delivery': 'التوصيل',
    'set.dEnabled': 'التوصيل شغال',
    'set.dEnabledHint': 'مقفول = إتمام الطلب متوقف على الموقع',
    'set.minOrder': 'أقل قيمة طلب',
    'set.freeAbove': 'توصيل مجاني فوق (عام)',
    'set.eta': 'مدة التوصيل المتوقعة',
    'set.payNote': 'طرق الدفع اللي العميل يقدر يختار منها عند إتمام الطلب:',
    'set.cash': 'كاش عند الاستلام',
    'set.card': 'بطاقة عند الاستلام',
    'set.payOne': 'لازم طريقة دفع واحدة على الأقل تفضل شغالة.',
    'set.note': 'ملاحظة التوصيل (بتظهر عند الطلب)',
    'set.enforced': 'الرسوم نفسها بتتحدد لكل منطقة في صفحة مناطق التوصيل — وقاعدة البيانات بتطبق كل ده وقت الطلب.',
    'set.rewards': 'نقاط الولاء',
    'set.rEnabled': 'برنامج الولاء شغال',
    'set.rPPO': 'نقاط كل طلب مكتمل',
    'set.rBonus': 'نقاط هدية التسجيل',
    'set.rValue': 'قيمة النقطة (جنيه) عند الاستبدال',
    'set.rMin': 'أقل نقاط لكل استبدال',
    'set.rMax': 'أكتر نقاط لكل استبدال',
    'set.rNote': 'العملاء بيجمعوا نقاط مع كل طلب مكتمل وبيستبدلوها كخصم عند الطلب. «قيمة النقطة» هي اللي بتحدد هل الشراء بالنقاط يستاهل — حط 0 لقفل الاستبدال.',
    'set.notifications': 'الإشعارات',
    'set.nSound': 'صوت الطلب الجديد',
    'set.nSoundHint': 'رنة في لوحة الجارسون لما طلب يوصل',
    'set.nBrowser': 'إشعارات المتصفح',
    'set.nBrowserHint': 'إشعار نظام حتى لو التبويب مش ظاهر',
    'set.todoTitle': 'قايمة شغل المكان',
    'set.todoIntro': 'الحاجات اللي البحث العام مقدرش يأكدها عن أكواريوم. خلصها واحدة واحدة:',
    'set.todoCount': '{d} من {t} خلصوا',
    'set.todoAllDone': 'كله خلص 🎉',
    'set.todoDel': 'شيل العنصر',
    'set.todoAdd': 'ضيف مهمة جديدة، مثال: «أكد مواعيد رمضان»…',
    'set.autosave': 'الإعدادات بتتحفظ تلقائيًا — الموقع وقاعدة البيانات بيقروا القيم دي بالظبط.',

    'ov.deliveriesToday': 'طلبات النهاردة',
    'ov.deliveriesTodaySub': 'طلبات من نص الليل',
    'ov.revenue': 'إيراد النهاردة',
    'ov.revenueSub': 'الطلبات المكتملة بس',
    'ov.activeDesc': 'طلبات نشطة',
    'ov.activeSub': 'محتاجة اهتمام دلوقتي',
    'ov.drivers': 'كباتن نشطين',
    'ov.driversSub': 'جاهزين للتوصيل',
    'ov.zones': 'مناطق التوصيل',
    'ov.zonesSub': 'شغالة دلوقتي',
    'ov.coupons': 'خصومات شغالة',
    'ov.couponsSub': 'تسجيل · كوبونات · تلقائي',
    'ov.members': 'أعضاء الولاء',
    'ov.membersSub': 'عملاء مسجلين',
    'ov.reviews': 'تقييمات مستنية',
    'ov.reviewsSub': 'في انتظار الموافقة',
    'ov.products': 'أصناف المنيو',
    'ov.productsSub': 'ظاهر / الإجمالي',
    'ov.itemsN': '{n} أصناف',
    'ov.recentEmpty': 'لسه مفيش طلبات توصيل — شارك لينك الطلب!',
    'ov.quickTitle': 'إجراءات سريعة',
    'ov.quickSub': 'ادخل على الشغل على طول',
    'ov.qDesign': 'صمم الموقع',
    'ov.qMenu': 'إدارة المنيو',
    'ov.qZones': 'المناطق والرسوم',
    'ov.qCoupons': 'الخصومات',
    'ov.qBanners': 'بانرات الرئيسية',
    'ov.qDrivers': 'الكباتن',
    'ov.qSettings': 'الإعدادات',
    'ov.qWaiter': 'لوحة الجارسون',
    'ov.recentTitle': 'أحدث الطلبات',
    'ov.recentSub': 'الأجدد الأول',
    'ov.watch': 'افتح متابعة التوصيل',
    'ov.todoTitle': 'قايمة شغل المكان',
    'ov.todoDone': '{d}/{t} خلصوا',
    'ov.todoOpen': 'افتح الإعدادات',
    'ov.todoMore': '+{n} كمان — شوف الإعدادات',
    'ov.todoEmpty': 'كل حاجة خلصت — برافو! 🎉',

    'dm.monitor': 'الطلبات المباشرة',
    'dm.monitorSub': 'للعرض بس · الحالات بتتحرك من لوحة الجارسون',
    'dm.searchPh': 'دور بالاسم أو التليفون أو العنوان أو المنطقة…',
    'dm.f.all': 'الكل',
    'dm.f.active': 'النشطة',
    'dm.f.done': 'المنتهية',
    'dm.reload': 'حدث',
    'dm.reloaded': 'اتحدث ✓',
    'dm.th.order': 'الطلب',
    'dm.th.customer': 'العميل',
    'dm.th.destination': 'الوجهة',
    'dm.th.captain': 'الكابتن',
    'dm.th.pay': 'الدفع',
    'dm.th.total': 'الإجمالي',
    'dm.th.status': 'الحالة',
    'dm.th.age': 'منى',
    'dm.cash': 'كاش',
    'dm.card': 'بطاقة',
    'dm.temp': 'مؤقت',
    'dm.member': 'عضو مسجل',
    'dm.feeLine': 'رسوم {v}',
    'dm.discountLine': 'خصم −{v}',
    'dm.pointsLine': '{n} نقطة مستخدمة',
    'dm.now': 'دلوقتي حالًا',
    'dm.mins': 'من {n} دقيقة',
    'dm.hours': 'من {n} ساعة',
    'dm.noResults': 'مفيش طلبات مطابقة للعرض ده.',
    'dm.loaded': 'طلبات محملة',
    'dm.loadedSub': 'أحدث 200',
    'dm.active': 'نشطة دلوقتي',
    'dm.activeSub': 'لسه مخلصتش',
    'dm.doneToday': 'اتوصلت النهاردة',
    'dm.doneTodaySub': 'من نص الليل',
    'dm.revenueToday': 'إيراد النهاردة',
    'dm.revenueTodaySub': 'طلبات مكتملة',
    'dm.items': 'الأصناف',
    'dm.noItems': '—',
    'dm.summary': 'الملخص',
    'dm.subtotal': 'المجموع الفرعي',
    'dm.discount': 'الخصم',
    'dm.fee': 'رسوم التوصيل',
    'dm.total': 'الإجمالي',
    'dm.eta': 'المدة المتوقعة',
    'dm.minUnit': 'دقيقة',
    'dm.pointsRedeemed': 'نقاط ولاء مستبدلة ({n} نقطة)',
    'dm.earnedOnDelivery': 'نقاط هتتكسب عند التوصيل',
    'dm.maps': 'افتح في الخريطة',

    /* ---- الكباتن ---- */
    'drv.addHd': 'أضف كابتن',
    'drv.addSub': 'الاسم والتليفون بس',
    'drv.name': 'اسم الكابتن',
    'drv.namePh': 'مثال: أحمد سامي',
    'drv.phone': 'التليفون',
    'drv.phonePh': 'مثال: +20 100 123 4567',
    'drv.notes': 'ملاحظات',
    'drv.notesPh': 'مثال: موتوسيكل · الفترة المسائية (اختياري)',
    'drv.add': 'أضف الكابتن',
    'drv.hint': 'بس الكباتن النشطين بيظهروا في لوحة الجارسون وقت التوصيل.',
    'drv.listHd': 'قايمة الكباتن',
    'drv.count': '{a} نشط من {n}',
    'drv.empty': 'مفيش كباتن لسه — ضيف أول كابتن توصيل من فوق.',
    'drv.errName': 'اكتب اسم الكابتن الأول (حرفين على الأقل).',
    'drv.errPhone': 'اكتب رقم تليفون صحيح (٨ أرقام على الأقل).',
    'drv.added': '{name} انضم للفريق 🛵',
    'drv.saved': '{name} اتحدث ✓',
    'drv.deleted': '{name} اتشال من القايمة',
    'drv.on': '{name} بقى نشط',
    'drv.off': '{name} اتوقف',
    'drv.active': 'متاح للتوصيل',
    'drv.editName': 'اسم الكابتن:',
    'drv.editPhone': 'رقم التليفون:',
    'drv.editNotes': 'ملاحظات (اختياري):',
    'drv.delTitle': 'تشيل {name}؟',
    'drv.delText': 'التوصيلات القديمة بتحتفظ بتاريخها. الكابتن بس مش هيظهر وقت التوصيل.',
    'drv.delYes': 'امسح الكابتن',
    'drv.note': 'محتاج كورير مؤقت؟ عند «جاهز للتوصيل» الجارسون يقدر يربط كابتن مؤقت بطلب واحد بس — ومبيدخلش القايمة دي أبدًا.',

    /* ---- محرر المحتوى ---- */
    'ct.about': 'قسم «من نحن»',
    'ct.title': 'العنوان',
    'ct.story': 'نص الحكاية',
    'ct.aboutImg': 'صورة «من نحن»',
    'ct.aboutImgHint': 'بتظهر جنب الحكاية',
    'ct.contact': 'التواصل',
    'ct.address': 'العنوان',
    'ct.email': 'الإيميل',
    'ct.wa': 'لينك الواتساب',
    'ct.maps': 'لينك جوجل مابس',
    'ct.phones': 'أرقام التليفون',
    'ct.addPhone': 'أضف رقم تليفون',
    'ct.phone': 'رقم تليفون',
    'ct.hours': 'مواعيد الشغل',
    'ct.days': 'الأيام',
    'ct.daysPh': 'السبت – الخميس',
    'ct.hoursLb': 'الساعات',
    'ct.hoursPh': '٨ ص – ١٢ م',
    'ct.addHours': 'أضف سطر مواعيد',
    'ct.hoursRow': 'سطر مواعيد',
    'ct.branches': 'الفروع',
    'ct.branch': 'الفرع',
    'ct.branchPh': 'الدهار — الفرع الرئيسي',
    'ct.branchAddrPh': 'شارع شيراتون…',
    'ct.branchPhonePh': '+٢٠ …',
    'ct.addBranch': 'أضف فرع',
    'ct.branchOne': 'فرع',
    'ct.socials': 'وسائل التواصل',
    'ct.socialsNote': 'لينكات السوشيال في جدول لوحدها بترتيب ومفاتيح ظهور — ديرها من',
    'ct.socialsPage': 'صفحة لينكات السوشيال ←',
    'ct.highlights': 'شريط المميزات',
    'ct.addPhrase': 'أضف جملة',
    'ct.phrase': 'جملة',
    'ct.highlightsHint': 'الشريط المتحرك بين الواجهة والمنيو.',
    'ct.footer': 'الفوتر',
    'ct.footerAbout': 'سطر «عن المكان» في الفوتر',
    'ct.footerAboutHint': 'بيظهر لو وصف الكافيه فاضي',
    'ct.autosave': 'المحتوى بيتحفظ تلقائيًا وانت بتكتب — وموقع العملاء بيتحدث في ثانية عن طريق Realtime.',
    'ct.editing': 'بتعدل…',

    /* ---- مكتبة الصور ---- */
    'md.copy': 'انسخ رابط الصورة',
    'md.replace': 'استبدل الصورة',
    'md.delete': 'امسح الصورة',
    'md.use': 'استخدم الصورة دي',
    'md.allFolders': 'كل المجلدات',
    'md.uploaded': '«{name}» اترفعت على /{folder}',
    'md.copied': 'رابط الصورة اتنسخ — الصقه في أي حتة',
    'md.replaced': '«{name}» اتبدلت — كل الأماكن اللي بتستخدمها هتتحدث',
    'md.delTitle': 'تحذف «{name}»؟',
    'md.delText': 'الملف بيتشال من التخزين. الأصناف أو الأقسام اللي بتستخدم رابطه هترجع لصورة بديلة.',
    'md.deleted': '«{name}» اتحذفت',
    'md.searchPh': 'دور على الصور…',
    'md.folderPh': 'اسم المجلد',
    'md.folderAria': 'مجلد الرفع',
    'md.upload': 'ارفع',
    'md.count': '{n} صورة',
    'md.count1': 'صورة واحدة',
    'md.emptyMatch': 'مفيش صور مطابقة — جرب مجلد أو بحث تاني.',
    'md.emptyLibrary': 'المكتبة فاضية — ارفع أول صورة.',
    'md.emptyPicker': 'مفيش صور هنا لسه — ارفع واحدة.',

    /* ---- البانرات ---- */
    'bn.formAdd': 'أضف بانر',
    'bn.formEdit': 'عدل البانر',
    'bn.formSub': 'شريط ترويجي على الصفحة الرئيسية',
    'bn.title': 'العنوان',
    'bn.titlePh': 'مثال: جمعة السي فود الطازة',
    'bn.subtitle': 'العنوان الفرعي',
    'bn.subtitlePh': 'مثال: كل جمعة من ٦ مساءً — لحد ما يخلص',
    'bn.image': 'صورة البانر',
    'bn.ctaText': 'نص الزرار (اختياري)',
    'bn.ctaTextPh': 'مثال: شوف المنيو',
    'bn.ctaLink': 'لينك الزرار (اختياري)',
    'bn.visible': 'ظاهر على الصفحة الرئيسية',
    'bn.save': 'احفظ البانر',
    'bn.add': 'أضف البانر',
    'bn.cancelEdit': 'إلغاء التعديل',
    'bn.saved': 'البانر اتحفظ ✓',
    'bn.added': 'البانر اتضاف 📣',
    'bn.deleted': 'البانر اتحذف',
    'bn.allHd': 'كل البانرات',
    'bn.allSub': 'أول بانر ظاهر هو اللي بيبان على الصفحة الرئيسية',
    'bn.empty': 'لسه مفيش بانرات — شريط العروض مخفي لحد ما تضيف واحد.',
    'bn.note': 'البانرات بتظهر تحت الواجهة في موقع العملاء. ضيف صورة حلوة من مكتبة الصور لأحسن نتيجة.',
    'bn.moveEarlier': 'قدم',
    'bn.moveLater': 'أخر',
    'bn.editAria': 'عدل البانر',
    'bn.delAria': 'امسح البانر',
    'bn.delTitle': 'تحذف البانر ده؟',
    'bn.delText': '«{title}» هيختفي من الصفحة الرئيسية.',
    'bn.delYes': 'امسح البانر',
    'bn.liveOn': 'البانر بقى ظاهر على الصفحة الرئيسية',
    'bn.liveOff': 'البانر اتخفى',

    /* ---- معرض الصور ---- */
    'gl.alt': 'صورة من المعرض',
    'gl.captionPh': 'تعليق (اختياري)',
    'gl.caption': 'التعليق',
    'gl.show': 'اظهر على الموقع',
    'gl.moveEarlier': 'قدم',
    'gl.moveLater': 'أخر',
    'gl.delAria': 'امسح الصورة',
    'gl.counts': '{n} صور · {v} ظاهرة',
    'gl.counts1': 'صورة واحدة · {v} ظاهرة',
    'gl.empty': 'لسه مفيش صور — ضيف الأكواريوم، فيو البحر، السمك الطازة…',
    'gl.addHd': 'أضف صورة',
    'gl.addSub': 'من مكتبة الصور أو من جهازك على طول',
    'gl.photo': 'الصورة',
    'gl.titlePh': 'مثال: الغروب على البحر الأحمر',
    'gl.add': 'أضف للمعرض',
    'gl.chooseFirst': 'اختار صورة الأول.',
    'gl.added': 'الصورة اتضافت للمعرض 📸',
    'gl.delTitle': 'تحذف الصورة دي؟',
    'gl.delTextT': '«{title}» هتخرج من المعرض العام.',
    'gl.delText': 'الصورة هتخرج من المعرض العام.',
    'gl.delYes': 'امسح الصورة',
    'gl.removed': 'الصورة اتشالت',
    'gl.captionSaved': 'التعليق اتحفظ',
    'gl.visibleOn': 'الصورة بقت ظاهرة على الموقع',
    'gl.visibleOff': 'الصورة اتخفت',
    'gl.note': 'الصور المخفية بتفضل هنا لوقت الحاجة — بس الظاهر بس اللي بيبان على الموقع، وبالترتيب ده.',

    /* ---- مراجعة التقييمات ---- */
    'rv2.approve': 'وافق وانشر',
    'rv2.unpublish': 'شيل من الموقع',
    'rv2.delete': 'امسح',
    'rv2.srcWebsite': 'الموقع',
    'rv2.srcDemo': 'عينة',
    'rv2.srcGoogle': 'جوجل',
    'rv2.srcManual': 'يدوي',
    'rv2.stPending': 'في انتظار الموافقة',
    'rv2.stPendingSub': 'مش ظاهرة للعملاء',
    'rv2.stLive': 'منشورة',
    'rv2.stLiveSub': 'على الموقع',
    'rv2.stAvg': 'المتوسط (المنشور)',
    'rv2.stAvgSub': 'جوجل بيظهر 4.2 ★',
    'rv2.pendingHd': 'في انتظار الموافقة',
    'rv2.pendingSub': 'تقييمات الموقع بتوصل هنا الأول',
    'rv2.liveHd': 'منشورة',
    'rv2.liveSub': 'ظاهرة على موقع العملاء',
    'rv2.inboxZero': 'مفيش حاجة مستنية موافقة. 🌊',
    'rv2.noLive': 'لسه مفيش تقييمات منشورة — وافق على واحد فوق، أو استنى أول تقييم من عميل.',
    'rv2.note': 'العملاء بيكتبوا تقييمات على الموقع — ولا واحد بينشر قبل ما توافق عليه هنا.',
    'rv2.live': 'تقييم {name} بقى منشور ⭐',
    'rv2.unpublished': 'التقييم اتشال من الموقع',
    'rv2.delTitle': 'تحذف التقييم ده؟',
    'rv2.cannotUndo': '— ومش ممكن ترجع فيه.',
    'rv2.delYes': 'امسح التقييم',
    'rv2.deleted': 'التقييم اتحذف',
    'rv2.guest': 'زائر',

    /* ---- لينكات السوشيال ---- */
    'so.choose': 'اختار المنصة…',
    'so.empty': 'لسه مفيش لينكات — ضيف صفحة الفيسبوك الأول، العملاء بيدوروا عليها.',
    'so.addHd': 'أضف لينك',
    'so.addSub': 'واحد لكل منصة',
    'so.urlPh': 'https://www.facebook.com/yourpage',
    'so.add': 'أضف اللينك',
    'so.hint': 'الحسابات الرسمية الحالية متسجلة مسبقًا — حدثها لو الملكية اتغيرت.',
    'so.allHd': 'كل اللينكات',
    'so.allSub': 'بتظهر في الفوتر وقسم التوصيل/التواصل، بالترتيب ده',
    'so.chooseFirst': 'اختار المنصة الأول.',
    'so.httpsWarn': 'اللينكات لازم تبدأ بـ https://',
    'so.added': 'لينك {platform} اتضاف 🔗',
    'so.delTitle': 'تحذف لينك {platform}؟',
    'so.delText': 'هيختفي من فوتر الموقع وقسم التواصل.',
    'so.delYes': 'امسح اللينك',
    'so.deleted': 'اللينك اتحذف',
    'so.saved': 'اللينك اتحفظ',
    'so.visibleOn': 'اللينك بقى ظاهر على الموقع',
    'so.visibleOff': 'اللينك اتخفى',
    'so.show': 'اظهر على الموقع',
    'so.moveUp': 'اطلع فوق',
    'so.moveDown': 'انزل تحت',
    'so.delAria': 'امسح اللينك',

    /* ---- المخصص ---- */
    'cz.live': 'معاينة مباشرة',
    'cz.deviceAria': 'مقاس المعاينة',
    'cz.desktop': 'معاينة كمبيوتر',
    'cz.mobile': 'معاينة موبايل',
    'cz.dirty': '● تغييرات غير محفوظة',
    'cz.reload': 'حدث المعاينة',
    'cz.openSite': 'افتح الموقع',
    'cz.reset': 'تراجع',
    'cz.save': 'احفظ التغييرات',
    'cz.saving': 'بيتحفظ…',
    'cz.savingState': 'الثيم بيتحفظ على Supabase…',
    'cz.unsavedState': 'في تغييرات غير محفوظة',
    'cz.savedState': 'كل التغييرات اتحفظت',
    'cz.savedToast': 'التصميم اتحفظ — مباشر على موقع العملاء ✦',
    'cz.discardTitle': 'تتجاهل التغييرات غير المحفوظة؟',
    'cz.discardText': 'اللوحات والمعاينة هترجع لآخر تصميم محفوظ.',
    'cz.discardYes': 'تجاهل',
    'cz.reverted': 'رجعنا للتصميم المحفوظ',
    'cz.hint1': 'كل تحكم بيرسم المعاينة فورًا — ومفيش حاجة بتتنشر غير لما تدوس',
    'cz.hint2': 'وتبويبات العملاء المفتوحة بتتحدث لوحدها.',
    'cz.tabsAria': 'لوحات المخصص',
    'cz.frameTitle': 'معاينة مباشرة لموقع العملاء',
    'cz.g.identity': 'هوية المكان',
    'cz.cafeName': 'اسم المكان',
    'cz.slogan': 'الشعار / الجملة',
    'cz.description': 'الوصف',
    'cz.copyright': 'سطر الحقوق',
    'cz.copyrightHint': 'استخدم {year} للسنة الحالية',
    'cz.g.logo': 'اللوجو والأيقونة',
    'cz.logo': 'اللوجو',
    'cz.logoHint': 'بيظهر في الشريط العلوي والفوتر',
    'cz.favicon': 'أيقونة التبويب',
    'cz.faviconHint': 'أيقونة تبويب المتصفح (المربع أحسن)',
    'cz.g.regional': 'إقليمي',
    'cz.currency': 'اسم العملة',
    'cz.g.palette': 'ألوان الهوية',
    'cz.primary': 'أساسي',
    'cz.secondary': 'ثانوي',
    'cz.accent': 'مميز',
    'cz.g.surfaces': 'الأسطح',
    'cz.background': 'الخلفية',
    'cz.sectionBg': 'خلفية الأقسام',
    'cz.cardBg': 'خلفية الكروت',
    'cz.border': 'الحدود',
    'cz.g.btnText': 'الأزرار والنصوص',
    'cz.buttonBg': 'لون الزرار',
    'cz.buttonHover': 'لون الزرار عند التمرير',
    'cz.text': 'النص',
    'cz.headings': 'العناوين',
    'cz.g.chrome': 'الإطار',
    'cz.navbarBg': 'الشريط العلوي',
    'cz.footerBg': 'الفوتر',
    'cz.overlay': 'غطاء النوافذ',
    'cz.g.fonts': 'عائلات الخطوط',
    'cz.headingFont': 'خط العناوين',
    'cz.bodyFont': 'خط النص',
    'cz.g.sizes': 'الأحجام والأوزان',
    'cz.bodySize': 'حجم النص',
    'cz.h1Size': 'عنوان الواجهة (H1)',
    'cz.h2Size': 'عنوان القسم (H2)',
    'cz.h3Size': 'عنوان الكارت (H3)',
    'cz.headingWeight': 'وزن العناوين',
    'cz.bodyWeight': 'وزن النص',
    'cz.g.rhythm': 'الإيقاع',
    'cz.letterSpacing': 'تباعد الحروف',
    'cz.lineHeight': 'ارتفاع السطر',
    'cz.g.canvas': 'اللوحة',
    'cz.containerWidth': 'عرض الحاوية',
    'cz.spacing': 'تباعد الشبكة',
    'cz.sectionPadding': 'حشوة الأقسام',
    'cz.g.cards': 'الكروت والعمق',
    'cz.cardRadius': 'استدارة الكروت',
    'cz.shadowSize': 'حجم الظل',
    'cz.gridColumns': 'أعمدة شبكة المنيو',
    'cz.g.heroBg': 'خلفية الواجهة',
    'cz.heroImage': 'صورة الواجهة',
    'cz.heroImageHint': 'لقطة بحر واسعة وهادية بتطلع أحلى',
    'cz.bgColor': 'لون الخلفية',
    'cz.overlayColor': 'لون الغطاء',
    'cz.overlayOpacity': 'تعتيم الغطاء',
    'cz.g.heroCopy': 'نص الواجهة',
    'cz.heroTitle': 'عنوان الواجهة',
    'cz.heroSubtitle': 'النص الفرعي',
    'cz.heroButton': 'نص الزرار',
    'cz.heroLink': 'لينك الزرار',
    'cz.heroLinkHint': '#menu أو #about… أو لينك كامل',
    'cz.g.barBehavior': 'سلوك الشريط',
    'cz.navbarStyle': 'ستايل الشريط العلوي',
    'cz.navGlass': 'زجاجي (مضبب)',
    'cz.navSolid': 'ثابت اللون',
    'cz.navTransparent': 'شفاف فوق الواجهة',
    'cz.sticky': 'لاصق',
    'cz.stickyHint': 'يفضل ثابت فوق وانت بتنزل',
    'cz.blur': 'تضبيب الخلفية',
    'cz.transparency': 'شفافية الخلفية',
    'cz.logoSize': 'حجم اللوجو',
    'cz.g.navItems': 'عناصر التنقل',
    'cz.navLabel': 'الاسم',
    'cz.navLabelPh': 'المنيو',
    'cz.navLink': 'اللينك',
    'cz.addNav': 'أضف لينك تنقل',
    'cz.navItemsHint': 'اللينكات الداخلية (#menu, #about, #contact) بتنزل جوه الصفحة؛ أي حاجة تانية بتتفتح في تبويب جديد.',
    'cz.g.cardDesign': 'تصميم الكارت',
    'cz.cardStyle': 'ستايل الكارت',
    'cz.cardElevated': 'مرتفع (بظل)',
    'cz.cardOutline': 'بحدود',
    'cz.cardFlat': 'مسطح / ملون',
    'cz.borderRadius': 'استدارة الحواف',
    'cz.shadow': 'الظل',
    'cz.hoverAnim': 'حركة التمرير',
    'cz.innerPadding': 'الحشوة الداخلية',
    'cz.g.cardImage': 'صورة الكارت',
    'cz.imageRatio': 'نسبة الصورة',
    'cz.imageSize': 'حجم الصورة',
    'cz.g.btnDesign': 'تصميم الأزرار',
    'cz.style': 'الستايل',
    'cz.styleSolid': 'ممتلئ',
    'cz.styleOutline': 'بحدود',
    'cz.styleSoft': 'ناعم (ملون)',
    'cz.size': 'الحجم',
    'cz.sizeS': 'صغير',
    'cz.sizeM': 'وسط',
    'cz.sizeL': 'كبير',
    'cz.animLift': 'رفعة',
    'cz.animScale': 'تكبير',
    'cz.animGlow': 'وهج',
    'cz.animNone': 'من غير',
    'cz.g.motion': 'الحركة',
    'cz.animEnabled': 'الحركات مفعّلة',
    'cz.animEnabledHint': 'مقفولة = عرض فوري ومريح',
    'cz.revealType': 'نوع الظهور',
    'cz.revealRise': 'صعود (من تحت)',
    'cz.revealFade': 'تلاشي',
    'cz.revealZoom': 'تقريب',
    'cz.revealSlide': 'انزلاق جانبي',
    'cz.baseDuration': 'المدة الأساسية',
    'cz.speed': 'السرعة',
    'cz.t.general': 'عام',
    'cz.t.colors': 'الألوان',
    'cz.t.typography': 'الخطوط',
    'cz.t.layout': 'التخطيط',
    'cz.t.hero': 'الواجهة',
    'cz.t.navbar': 'الشريط العلوي',
    'cz.t.cards': 'كارت المنتج',
    'cz.t.buttons': 'الأزرار',
    'cz.t.animations': 'الحركات',

    'g.fontPreview': 'Aa — نص تجريبي للخط 01234',
  },
};
