// ============================================================
//  Aquarium Cafe & Resturant — Customer dictionary (EN + AR)
//  Every UI string on the site: nav, buttons, forms, hints,
//  validation, statuses, toasts — nothing user-facing is left
//  hardcoded. Keys are flat dot-paths consumed by shared/i18n.js
//  via data-i18n attributes in HTML and t() in JS.
// ============================================================

export const dictionary = {
  /* ════════════════════ ENGLISH ════════════════════ */
  en: {
    /* ---- nav / chrome ---- */
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.gallery': 'Gallery',
    'nav.about': 'About',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    'nav.signin': 'Sign in',
    'nav.account': 'My account',
    'nav.cart': 'Open your cart',
    'nav.burger': 'Open menu',
    'nav.lang': 'التبديل إلى العربية',
    'nav.trackPill': 'Track your order',
    'nav.trackPillOnway': 'On the way — track it',
    'nav.brandHome': 'Restaurant home',

    /* ---- hero (static chrome only; texts come from the CMS) ---- */
    'hero.scroll': 'Scroll down',
    'hero.statRating': 'Google rating · 800+ reviews',
    'hero.statItems': 'Menu items',
    'hero.statHours': '8 AM – 2 AM',
    'hero.statOpen': 'Open daily',

    /* ---- menu section ---- */
    'menu.eyebrow': '— The Menu —',
    'menu.titleHtml': 'From the <em>sea &amp; the bar</em>',
    'menu.sub': 'Real prices, straight off our paper menu — hot drinks, thick smoothies, shisha and every extra you can add. Tap an item to see it up close.',
    'menu.searchPh': 'Search the menu…',
    'menu.sort': 'Sort the menu',
    'menu.sortDefault': 'Sort: House order',
    'menu.sortPriceAsc': 'Price: low → high',
    'menu.sortPriceDesc': 'Price: high → low',
    'menu.sortName': 'Name: A → Z',
    'menu.chips': 'Menu categories',
    'menu.vatNotice': '14% VAT taxes will be added.',
    'chip.all': 'All',
    'chip.favorites': 'Favorites',
    'chip.featured': 'Featured',
    'menu.noResultsTitle': 'Nothing matches that',
    'menu.noResultsSub': 'Try another word — or clear the search.',
    'menu.favEmptyTitle': 'No favorites yet',
    'menu.favEmptySub': 'Tap the ♥ on any dish you love.',
    'menu.catEmptyTitle': 'Nothing here yet',
    'menu.catEmptySub': 'Check another category.',
    'menu.loadError': 'Could not load the menu.',
    'menu.retry': 'Try again',
    'menu.loading': 'Loading the menu…',
    'fav.add': 'Add to favorites',
    'fav.remove': 'Remove from favorites',
    'card.details': 'View details',
    'card.addAria': 'Add {name} to your order',
    'gal.empty': 'Photos are on their way — check back soon.',
    'gal.viewPhoto': 'View photo {n}',
    'rv.empty': 'No reviews yet — be the first to share your visit below.',
    'rv.publishing': 'Publishing…',
    'rv.failed': 'Could not publish — please try again.',

    /* ---- product modal ---- */
    'pm.title': 'Product details',
    'pm.qty': 'Quantity',
    'pm.minus': 'Decrease quantity',
    'pm.plus': 'Increase quantity',
    'pm.add': 'Add to Order',
    'pm.close': 'Close',

    /* ---- cart drawer ---- */
    'cart.title': 'Your Order',
    'cart.close': 'Close cart',
    'cart.emptyTitle': 'Your cart is empty',
    'cart.emptySub': 'Something from the sea? A smoothie? Add it from the menu.',
    'cart.browse': 'Browse the menu',
    'cart.total': 'Total',
    'cart.note': 'Home delivery across Hurghada — pay when it arrives 🌊',
    'cart.checkout': 'Checkout',
    'cart.decrease': 'Decrease',
    'cart.increase': 'Increase',
    'cart.remove': 'Remove {name}',
    'cart.itemCount': '· {n} item',
    'cart.itemCountPlural': '· {n} items',

    /* ---- delivery checkout ---- */
    'dl.title': 'Delivery details',
    'dl.summary': "{n} item · home delivery",
    'dl.summaryPlural': '{n} items · home delivery',
    'dl.steps': 'Delivery address in 3 steps',
    'dl.step1': 'Zone',
    'dl.step2': 'Sub zone',
    'dl.step3': 'Address',
    'dl.zoneHint': 'Choose your zone — the delivery fee is set per zone.',
    'dl.subHint': 'Pick your sub area — it helps the captain find you faster.',
    'dl.subSkip': 'No sub area needed',
    'dl.subNone': 'No sub areas here yet — just continue.',
    'dl.back': 'Back',
    'dl.next': 'Continue',
    'dl.feePerZone': 'Fee',
    'dl.freeAbove': 'Free over {x}',
    'dl.name': 'Full Name',
    'dl.namePh': 'e.g. Sara Adel',
    'dl.phone': 'Phone Number',
    'dl.phonePh': '+20 10…',
    'dl.address': 'Detailed Address',
    'dl.addressPh': 'Building 5, apartment 8, third floor, next to the pharmacy…',
    'dl.maps': 'Google Maps link',
    'dl.mapsOpt': 'optional — helps the captain find you',
    'dl.mapsPh': 'https://maps.google.com/…',
    'dl.notes': 'Notes',
    'dl.notesOpt': 'optional',
    'dl.notesPh': 'No onions, ring the bell twice…',
    'dl.pay': 'Payment method',
    'pay.cash': 'Cash on delivery',
    'pay.card_on_delivery': 'Card on delivery',
    'dl.couponPh': 'Coupon code (optional)',
    'dl.couponApply': 'Apply',
    'dl.couponApplied': '{label} — you save {x}',
    'dl.pointsTitle': 'Loyalty points',
    'dl.pointsHave': 'You have {n} points',
    'dl.pointsUse': 'Use points on this order',
    'dl.pointsRange': 'min {min} · max {max} · 1 pt = {v}',
    'dl.pointsApplied': 'Using {n} points (−{x})',
    'dl.signinNudge': 'Sign in to collect points on every order and use member coupons.',
    'dl.signinBtn': 'Sign in / Create account',
    'dl.earn': "You'll earn {n} points with this order 🎁",
    'dl.subtotal': 'Subtotal',
    'dl.discount': 'Discount',
    'dl.pointsOff': 'Points discount',
    'dl.fee': 'Delivery fee',
    'dl.feeFree': 'Free 🎉',
    'dl.total': 'Total',
    'dl.eta': '≈ {n} min to your door',
    'dl.minOrder': 'min order {x}',
    'dl.submit': 'Place delivery order',
    'dl.sending': 'Sending to the kitchen…',
    'dl.doneTitle': 'Order received!',
    'dl.doneSub': 'The kitchen has it — follow every step live.',
    'dl.doneOrder': 'Order',
    'dl.doneTotal': 'Total',
    'dl.donePayment': 'Payment',
    'dl.donePoints': 'Loyalty',
    'dl.donePointsLine': 'used {used} · will earn {earn}',
    'dl.track': 'Track my order live',
    'dl.backToMenu': 'Back to the menu',

    /* ---- client-side validation ---- */
    'val.zone': 'Please choose your delivery zone first.',
    'val.subzone': 'Please pick a sub zone, or tap “{skip}”.',
    'val.name': 'Please enter your full name.',
    'val.phone': 'Please enter a valid phone number.',
    'val.address': 'Please write your full address (building, apartment, floor, landmark).',
    'val.maps': 'The maps link must start with http:// or https://',
    'val.payment': 'Please choose a payment method.',
    'val.email': 'Please enter a valid email address.',
    'val.password': 'Password needs at least 6 characters.',
    'val.pointsMin': 'Minimum redemption is {n} points.',
    'val.pointsMax': 'Maximum redemption per order is {n} points.',
    'val.pointsBalance': 'Not enough points — your balance is {n}.',

    /* ---- coupon server keys (validate_coupon) ---- */
    'coupon.empty': 'Enter a coupon code.',
    'coupon.auth': 'Please sign in again.',
    'coupon.cart': 'Your cart is empty or has unavailable items.',
    'coupon.invalid': 'This coupon code is invalid or has expired.',
    'coupon.min_order': 'This coupon needs a minimum order of {min}.',
    'coupon.signup_only': 'This coupon is for registered customers — please sign in.',
    'coupon.first_order': 'This welcome coupon works on your first order only.',
    'coupon.not_applicable': 'This coupon does not apply to the items in your cart.',

    /* ---- tracking ---- */
    'tk.title': 'Live tracking',
    'tk.order': 'Order',
    'tk.live': 'LIVE',
    'tk.eta': 'estimated ≈ {n} min',
    'tk.enjoy': 'Enjoy your meal!',
    'tk.callIfMistake': 'Call us if this is a mistake',
    'tk.history': 'Order journey',
    'tk.connecting': 'Connecting…',
    'tk.driverYou': 'Your delivery captain',
    'tk.call': 'Call captain',
    'tk.earned': 'You earned {n} points on this order 🎉',
    'tk.onway': 'On the way to you 🛵',
    'tk.justNow': 'just now',
    'tk.minAgo': '{n} min ago',
    'tk.hAgo': '{h}h {m}m ago',
    'tk.zone': 'Delivering to {name}',
    'tk.summary': '{n} items · {total}',
    'tk.progress': 'Order progress',

    /* ---- statuses (server-side values stay English) ---- */
    'status.Received': 'Received',
    'status.Accepted': 'Accepted',
    'status.Preparing': 'Preparing',
    'status.Ready': 'Ready',
    'status.Out for Delivery': 'Out for Delivery',
    'status.Delivered': 'Delivered',
    'status.Cancelled': 'Cancelled',

    /* ---- auth modal ---- */
    'auth.title': 'Your account',
    'auth.inTab': 'Sign in',
    'auth.upTab': 'Create account',
    'auth.inSub': 'Sign in to collect loyalty points and use member coupons.',
    'auth.upSub': 'A free account — earn points on every order and unlock member rewards.',
    'auth.name': 'Full name',
    'auth.namePh': 'e.g. Sara Adel',
    'auth.phone': 'Phone number',
    'auth.phonePh': '+20 10…',
    'auth.email': 'Email',
    'auth.emailPh': 'you@example.com',
    'auth.password': 'Password',
    'auth.passwordPh': '6+ characters',
    'auth.signin': 'Sign in',
    'auth.signup': 'Create my account',
    'auth.working': 'One moment…',
    'auth.or': 'or',
    'auth.guest': 'Continue as guest',
    'auth.welcome': 'Ahlan, {name}! 👋',
    'auth.signedUp': 'Account created — welcome to Aquarium 🌊',
    'auth.confirmEmail': 'Account created ✓ — confirm it from the email we just sent, then sign in.',
    'auth.bonus': '+{n} welcome points landed in your wallet 🎁',
    'auth.signedOut': 'Signed out — see you soon!',
    'auth.err.credentials': 'Wrong email or password.',
    'auth.err.exists': 'This email already has an account — try signing in.',
    'auth.err.weak': 'Password needs at least 6 characters.',
    'auth.err.generic': 'Could not reach the server — please try again.',

    /* ---- profile modal ---- */
    'pf.title': 'My profile',
    'pf.member': 'Aquarium member',
    'pf.name': 'Full name',
    'pf.phone': 'Phone number',
    'pf.save': 'Save changes',
    'pf.saved': 'Profile saved ✓',
    'pf.points': 'Loyalty points',
    'pf.pts': '{n} pts',
    'pf.worth': 'worth {x}',
    'pf.earnRate': 'you earn {n} pts on every delivered order',
    'pf.history': 'Points history',
    'pf.all': 'All',
    'pf.earned': 'Earned',
    'pf.redeemed': 'Redeemed',
    'pf.empty': 'No points movement yet — order something tasty first.',
    'pf.signout': 'Sign out',
    'reason.signup_bonus': 'Welcome bonus',
    'reason.earn': 'Points earned on a delivered order',
    'reason.redeem': 'Redeemed on an order',
    'reason.refund': 'Order cancelled — points returned',
    'reason.admin': 'Adjustment by the team',

    /* ---- gallery / about / reviews / contact ---- */
    'gal.eyebrow': '— Gallery —',
    'gal.titleHtml': 'Moments on the <em>water</em>',
    'gal.sub': 'Terrace sunsets, the day’s catch and shisha smoke over the Red Sea.',
    'gal.viewer': 'Photo viewer',
    'about.eyebrow': '— Our Story —',
    'about.badge': 'Fresh every day',
    'about.browse': 'Browse the menu',
    'rv.eyebrow': '— Guest Book —',
    'rv.titleHtml': 'What our <em>guests say</em>',
    'rv.subHtml': 'Rated <strong>4.2★ on Google</strong> from 800+ visitors — and counting.',
    'rv.write': 'Write a review',
    'rv.note': 'New reviews appear after the team approves them.',
    'rv.modalTitle': 'Share your visit',
    'rv.modalSub': 'Published after a quick look from our team.',
    'rv.rating': 'Your rating',
    'rv.star': '{n} star',
    'rv.stars': '{n} stars',
    'rv.name': 'Your name',
    'rv.namePh': 'e.g. Mona',
    'rv.text': 'Your review',
    'rv.textPh': 'How was the seafood? The terrace? The shisha?',
    'rv.submit': 'Publish review',
    'rv.success': 'Thank you! Your review is waiting for approval 💙',
    'val.rvName': 'Please tell us your name.',
    'val.rvRating': 'Please pick a star rating.',
    'val.rvText': 'A few words help — write a short review.',

    /* ---- contact / footer ---- */
    'c.eyebrow': '— Find Us —',
    'c.titleHtml': 'Come say <em>ahlan</em>',
    'c.sub': 'On the corniche behind the General Hospital — walk up the stairs and the sea does the rest.',
    'c.address': 'Address',
    'c.walkins': 'Walk-ins always welcome',
    'c.contact': 'Contact',
    'c.hours': 'Working Hours',
    'c.follow': 'Follow Us',
    'c.whatsapp': 'WhatsApp',
    'c.email': 'Email us',
    'c.branches': 'Our Branches',
    'c.maps': 'Open in Google Maps',
    'c.socialHint': 'Daily catch & terrace sunsets',
    'ft.explore': 'Explore',
    'ft.hours': 'Working Hours',
    'ft.contact': 'Contact',
    'ft.home': 'Home',
    'ft.menu': 'Digital Menu',
    'ft.gallery': 'Gallery',
    'ft.contactLink': 'Contact & Location',
    'misc.toTop': 'Back to top',
    'misc.close': 'Close',

    /* ---- toasts / misc ---- */
    'msg.added': '{name} added to your order',
    'msg.removed': '{name} removed',
    'msg.cartEmpty': 'Your cart is empty',
    'msg.orderPlaced': 'Order received — the kitchen has it!',
    'msg.deliveryOff': 'Delivery is temporarily unavailable — call us and we’ll take your order.',
    'msg.comingSoon': 'coming soon',
  },

  /* ════════════════════ ARABIC ════════════════════ */
  ar: {
    /* ---- nav / chrome ---- */
    'nav.home': 'الرئيسية',
    'nav.menu': 'المنيو',
    'nav.gallery': 'المعرض',
    'nav.about': 'من نحن',
    'nav.reviews': 'آراء العملاء',
    'nav.contact': 'تواصل معنا',
    'nav.signin': 'تسجيل الدخول',
    'nav.account': 'حسابي',
    'nav.cart': 'افتح السلة',
    'nav.burger': 'افتح القائمة',
    'nav.lang': 'Switch to English',
    'nav.trackPill': 'تابع طلبك',
    'nav.trackPillOnway': 'في الطريق إليك — تابعه',
    'nav.brandHome': 'الصفحة الرئيسية للمطعم',

    /* ---- hero ---- */
    'hero.scroll': 'انزل لتحت',
    'hero.statRating': 'تقييم جوجل · أكثر من ٨٠٠ مراجعة',
    'hero.statItems': 'صنف في المنيو',
    'hero.statHours': '٨ ص – ٢ ص',
    'hero.statOpen': 'مفتوحين كل يوم',

    /* ---- menu section ---- */
    'menu.eyebrow': '— المنيو —',
    'menu.titleHtml': 'من <em>البحر والبار</em>',
    'menu.sub': 'أسعار حقيقية من منيو الورق على طول — مشروبات ساخنة، سموزي تقيل، شيشة وكل الإضافات. دوس على أي صنف تشوفه عن قرب.',
    'menu.searchPh': 'دوّر في المنيو…',
    'menu.sort': 'رتّب المنيو',
    'menu.sortDefault': 'الترتيب: ترتيب المكان',
    'menu.sortPriceAsc': 'السعر: من الأقل للأعلى',
    'menu.sortPriceDesc': 'السعر: من الأعلى للأقل',
    'menu.sortName': 'الاسم: أ → ي',
    'menu.chips': 'أقسام المنيو',
    'menu.vatNotice': 'يضاف ١٤% ضريبة قيمة مضافة.',
    'chip.all': 'الكل',
    'chip.favorites': 'المفضلة',
    'chip.featured': 'المميز',
    'menu.noResultsTitle': 'مفيش نتيجة كده',
    'menu.noResultsSub': 'جرّب كلمة تانية — أو امسح البحث.',
    'menu.favEmptyTitle': 'مفيش مفضلات لسه',
    'menu.favEmptySub': 'دوس على ♥ في أي صنف يعجبك.',
    'menu.catEmptyTitle': 'مفيش حاجة هنا لسه',
    'menu.catEmptySub': 'جرّب قسم تاني.',
    'menu.loadError': 'مش قادرين نحمّل المنيو.',
    'menu.retry': 'حاول تاني',
    'menu.loading': 'بنحمّل المنيو…',
    'fav.add': 'ضيف للمفضلة',
    'fav.remove': 'شيل من المفضلة',
    'card.details': 'شوف التفاصيل',
    'card.addAria': 'ضيف {name} لطلبك',
    'gal.empty': 'الصور في السكة — ارجع تاني قريب.',
    'gal.viewPhoto': 'شوف الصورة {n}',
    'rv.empty': 'لسه مفيش آراء — كون أول واحد يشاركنا زيارته تحت.',
    'rv.publishing': 'بننشر…',
    'rv.failed': 'مش قادرين ننشر — حاول تاني لو سمحت.',

    /* ---- product modal ---- */
    'pm.title': 'تفاصيل الصنف',
    'pm.qty': 'الكمية',
    'pm.minus': 'قلّل الكمية',
    'pm.plus': 'زوّد الكمية',
    'pm.add': 'ضيف للطلب',
    'pm.close': 'اقفل',

    /* ---- cart drawer ---- */
    'cart.title': 'طلبك',
    'cart.close': 'اقفل السلة',
    'cart.emptyTitle': 'سلتك فاضية',
    'cart.emptySub': 'حاجة من البحر؟ سموزي؟ ضيفها من المنيو.',
    'cart.browse': 'تصفّح المنيو',
    'cart.total': 'الإجمالي',
    'cart.note': 'توصيل لحد البيت في كل الغردقة — الدفع عند الاستلام 🌊',
    'cart.checkout': 'إتمام الطلب',
    'cart.decrease': 'قلّل',
    'cart.increase': 'زوّد',
    'cart.remove': 'شيل {name}',
    'cart.itemCount': '· {n} صنف',
    'cart.itemCountPlural': '· {n} أصناف',

    /* ---- delivery checkout ---- */
    'dl.title': 'تفاصيل التوصيل',
    'dl.summary': '{n} صنف · توصيل للبيت',
    'dl.summaryPlural': '{n} أصناف · توصيل للبيت',
    'dl.steps': 'عنوان التوصيل في ٣ خطوات',
    'dl.step1': 'المنطقة',
    'dl.step2': 'المنطقة الفرعية',
    'dl.step3': 'العنوان',
    'dl.zoneHint': 'اختار منطقتك — رسوم التوصيل بتتحدد حسب المنطقة.',
    'dl.subHint': 'اختار المنطقة الفرعية — بتساعد الكابتن يوصلك أسرع.',
    'dl.subSkip': 'مفيش منطقة فرعية محددة',
    'dl.subNone': 'مفيش مناطق فرعية هنا لسه — كمّل عادي.',
    'dl.back': 'رجوع',
    'dl.next': 'التالي',
    'dl.feePerZone': 'الرسوم',
    'dl.freeAbove': 'مجاني فوق {x}',
    'dl.name': 'الاسم بالكامل',
    'dl.namePh': 'مثال: سارة عادل',
    'dl.phone': 'رقم الموبايل',
    'dl.phonePh': '+20 10…',
    'dl.address': 'العنوان بالتفصيل',
    'dl.addressPh': 'عمارة ٥، شقة ٨، الدور التالت، جنب الصيدلية…',
    'dl.maps': 'لينك جوجل مابس',
    'dl.mapsOpt': 'اختياري — بيساعد الكابتن يوصلك',
    'dl.mapsPh': 'https://maps.google.com/…',
    'dl.notes': 'ملاحظات',
    'dl.notesOpt': 'اختياري',
    'dl.notesPh': 'من غير بصل، اقرع الجرس مرتين…',
    'dl.pay': 'طريقة الدفع',
    'pay.cash': 'كاش عند الاستلام',
    'pay.card_on_delivery': 'كارت عند الاستلام',
    'dl.couponPh': 'كود الخصم (اختياري)',
    'dl.couponApply': 'طبّق',
    'dl.couponApplied': '{label} — وفّرت {x}',
    'dl.pointsTitle': 'نقاط الولاء',
    'dl.pointsHave': 'معاك {n} نقطة',
    'dl.pointsUse': 'استخدم نقاط في الطلب ده',
    'dl.pointsRange': 'أقل {min} · أقصى {max} · النقطة = {v}',
    'dl.pointsApplied': 'بتستخدم {n} نقطة (−{x})',
    'dl.signinNudge': 'سجّل دخولك عشان تجمّع نقاط مع كل طلب وتستخدم كوبونات الأعضاء.',
    'dl.signinBtn': 'تسجيل دخول / حساب جديد',
    'dl.earn': 'هتكسب {n} نقطة مع الطلب ده 🎁',
    'dl.subtotal': 'المجموع الفرعي',
    'dl.discount': 'الخصم',
    'dl.pointsOff': 'خصم النقاط',
    'dl.fee': 'رسوم التوصيل',
    'dl.feeFree': 'مجاني 🎉',
    'dl.total': 'الإجمالي',
    'dl.eta': 'حوالي {n} دقيقة لحد باب البيت',
    'dl.minOrder': 'أقل طلب {x}',
    'dl.submit': 'اطلب التوصيل',
    'dl.sending': 'بنبعت للمطبخ…',
    'dl.doneTitle': 'استلمنا طلبك!',
    'dl.doneSub': 'المطبخ بيجهزه — تابع كل خطوة لايف.',
    'dl.doneOrder': 'الطلب',
    'dl.doneTotal': 'الإجمالي',
    'dl.donePayment': 'الدفع',
    'dl.donePoints': 'النقاط',
    'dl.donePointsLine': 'استخدمت {used} · هتكسب {earn}',
    'dl.track': 'تابع طلبي لايف',
    'dl.backToMenu': 'ارجع للمنيو',

    /* ---- client-side validation ---- */
    'val.zone': 'لو سمحت اختار منطقة التوصيل الأول.',
    'val.subzone': 'اختار المنطقة الفرعية، أو دوس «{skip}».',
    'val.name': 'لو سمحت اكتب اسمك بالكامل.',
    'val.phone': 'لو سمحت اكتب رقم موبايل صح.',
    'val.address': 'لو سمحت اكتب عنوانك كامل (عمارة، شقة، دور، علامة مميزة).',
    'val.maps': 'لينك الخريطة لازم يبدأ بـ http:// أو https://',
    'val.payment': 'لو سمحت اختار طريقة الدفع.',
    'val.email': 'لو سمحت اكتب بريد إلكتروني صح.',
    'val.password': 'كلمة السر لازم ٦ حروف على الأقل.',
    'val.pointsMin': 'أقل استبدال {n} نقطة.',
    'val.pointsMax': 'أقصى استبدال في الطلب {n} نقطة.',
    'val.pointsBalance': 'نقاطك مش كفاية — رصيدك {n}.',

    /* ---- coupon server keys ---- */
    'coupon.empty': 'اكتب كود الخصم.',
    'coupon.auth': 'سجّل دخولك من جديد لو سمحت.',
    'coupon.cart': 'سلتك فاضية أو فيها أصناف مش متاحة.',
    'coupon.invalid': 'كود الخصم ده غلط أو منتهي.',
    'coupon.min_order': 'الكود ده محتاج أقل طلب {min}.',
    'coupon.signup_only': 'الكوبون ده لعملاء الموقع المسجلين — سجّل دخولك لو سمحت.',
    'coupon.first_order': 'كوبون الترحيب بيشتغل مع أول طلب بس.',
    'coupon.not_applicable': 'الكوبون ده مش بيخص الأصناف اللي في سلتك.',

    /* ---- tracking ---- */
    'tk.title': 'متابعة لايف',
    'tk.order': 'الطلب',
    'tk.live': 'لايف',
    'tk.eta': 'الوصول المتوقع ≈ {n} دقيقة',
    'tk.enjoy': 'بالهنا والشفا!',
    'tk.callIfMistake': 'كلمنا لو فيه غلط',
    'tk.history': 'رحلة الطلب',
    'tk.connecting': 'جاري الاتصال…',
    'tk.driverYou': 'كابتن التوصيل بتاعك',
    'tk.call': 'كلم الكابتن',
    'tk.earned': 'كسبت {n} نقطة من الطلب ده 🎉',
    'tk.onway': 'في الطريق إليك 🛵',
    'tk.justNow': 'دلوقتي حالًا',
    'tk.minAgo': 'من {n} دقيقة',
    'tk.hAgo': 'من {h} ساعة و {m} دقيقة',
    'tk.zone': 'التوصيل إلى {name}',
    'tk.summary': '{n} أصناف · {total}',
    'tk.progress': 'تقدّم الطلب',

    /* ---- statuses ---- */
    'status.Received': 'استلمنا الطلب',
    'status.Accepted': 'تم القبول',
    'status.Preparing': 'جاري التجهيز',
    'status.Ready': 'جاهز',
    'status.Out for Delivery': 'خرج للتوصيل',
    'status.Delivered': 'تم التوصيل',
    'status.Cancelled': 'أُلغي',

    /* ---- auth modal ---- */
    'auth.title': 'حسابك',
    'auth.inTab': 'تسجيل الدخول',
    'auth.upTab': 'حساب جديد',
    'auth.inSub': 'سجّل دخولك عشان تجمّع نقاط الولاء وتستخدم كوبونات الأعضاء.',
    'auth.upSub': 'حساب مجاني — اكسب نقاط مع كل طلب وافتح مكافآت الأعضاء.',
    'auth.name': 'الاسم بالكامل',
    'auth.namePh': 'مثال: سارة عادل',
    'auth.phone': 'رقم الموبايل',
    'auth.phonePh': '+20 10…',
    'auth.email': 'البريد الإلكتروني',
    'auth.emailPh': 'you@example.com',
    'auth.password': 'كلمة السر',
    'auth.passwordPh': '٦ أحرف أو أكثر',
    'auth.signin': 'تسجيل الدخول',
    'auth.signup': 'اعمل حسابي',
    'auth.working': 'لحظة واحدة…',
    'auth.or': 'أو',
    'auth.guest': 'كمّل كزائر',
    'auth.welcome': 'أهلًا يا {name}! 👋',
    'auth.signedUp': 'اتعمل حسابك — أهلًا بيك في أكواريوم 🌊',
    'auth.confirmEmail': 'اتعمل حسابك ✓ — أكّده من الإيميل اللي وصلك، وبعدين سجّل دخولك.',
    'auth.bonus': '+{n} نقطة ترحيب نزلوا محفظتك 🎁',
    'auth.signedOut': 'سجّلنا خروجك — نشوفك قريب!',
    'auth.err.credentials': 'البريد أو كلمة السر غلط.',
    'auth.err.exists': 'البريد ده ليه حساب بالفعل — جرّب تسجل دخولك.',
    'auth.err.weak': 'كلمة السر لازم ٦ أحرف على الأقل.',
    'auth.err.generic': 'مش قادرين نوصل للسيرفر — جرّب تاني لو سمحت.',

    /* ---- profile modal ---- */
    'pf.title': 'حسابي',
    'pf.member': 'عضو أكواريوم',
    'pf.name': 'الاسم بالكامل',
    'pf.phone': 'رقم الموبايل',
    'pf.save': 'احفظ التعديل',
    'pf.saved': 'اتحفظت البيانات ✓',
    'pf.points': 'نقاط الولاء',
    'pf.pts': '{n} نقطة',
    'pf.worth': 'قيمتها {x}',
    'pf.earnRate': 'بتكسب {n} نقطة مع كل طلب يوصل',
    'pf.history': 'سجل النقاط',
    'pf.all': 'الكل',
    'pf.earned': 'مكتسبة',
    'pf.redeemed': 'مستخدمة',
    'pf.empty': 'لسه مفيش حركة نقاط — اطلب حاجة حلوة الأول.',
    'pf.signout': 'تسجيل الخروج',
    'reason.signup_bonus': 'مكافأة الترحيب',
    'reason.earn': 'نقاط مكتسبة من طلب وصل',
    'reason.redeem': 'نقاط مستخدمة في طلب',
    'reason.refund': 'الطلب اتلغى — النقاط رجعت',
    'reason.admin': 'تعديل من الإدارة',

    /* ---- gallery / about / reviews / contact ---- */
    'gal.eyebrow': '— المعرض —',
    'gal.titleHtml': 'لحظات على <em>المية</em>',
    'gal.sub': 'غروب التراس، صيد النهارده، ودخان الشيشة فوق البحر الأحمر.',
    'gal.viewer': 'عارض الصور',
    'about.eyebrow': '— حكايتنا —',
    'about.badge': 'طازة كل يوم',
    'about.browse': 'تصفّح المنيو',
    'rv.eyebrow': '— دفتر الضيوف —',
    'rv.titleHtml': 'ضيوفنا <em>بيقولوا إيه</em>',
    'rv.subHtml': 'متقيّم <strong>٤٫٢★ على جوجل</strong> من أكتر من ٨٠٠ زائر — والعدّاد شغال.',
    'rv.write': 'اكتب رأيك',
    'rv.note': 'المراجعات الجديدة بتظهر بعد موافقة الإدارة.',
    'rv.modalTitle': 'احكيلنا عن زيارتك',
    'rv.modalSub': 'بتتنشر بعد نظرة سريعة من فريقنا.',
    'rv.rating': 'تقييمك',
    'rv.star': 'نجمة واحدة',
    'rv.stars': '{n} نجوم',
    'rv.name': 'اسمك',
    'rv.namePh': 'مثال: منى',
    'rv.text': 'رأيك',
    'rv.textPh': 'إيه رأيك في السمك؟ التراس؟ الشيشة؟',
    'rv.submit': 'انشر رأيك',
    'rv.success': 'شكرًا! رأيك مستني الموافقة 💙',
    'val.rvName': 'قولنا اسمك لو سمحت.',
    'val.rvRating': 'اختار عدد النجوم لو سمحت.',
    'val.rvText': 'كلمتين هيفرقوا — اكتب رأي قصير.',

    /* ---- contact / footer ---- */
    'c.eyebrow': '— مكاننا —',
    'c.titleHtml': 'تعالى قول <em>أهلًا</em>',
    'c.sub': 'على الكورنيش ورا المستشفى العام — اطلع السلم والبحر هياخدك على طول.',
    'c.address': 'العنوان',
    'c.walkins': 'الزيارة المباشرة دايمًا مرحّبة',
    'c.contact': 'التواصل',
    'c.hours': 'مواعيد العمل',
    'c.follow': 'تابعنا',
    'c.whatsapp': 'واتساب',
    'c.email': 'ابعتلنا إيميل',
    'c.branches': 'فروعنا',
    'c.maps': 'افتح في جوجل مابس',
    'c.socialHint': 'صيد اليوم وغروب التراس',
    'ft.explore': 'استكشف',
    'ft.hours': 'مواعيد العمل',
    'ft.contact': 'تواصل معنا',
    'ft.home': 'الرئيسية',
    'ft.menu': 'المنيو الرقمي',
    'ft.gallery': 'المعرض',
    'ft.contactLink': 'التواصل والموقع',
    'misc.toTop': 'ارجع لفوق',
    'misc.close': 'اقفل',

    /* ---- toasts / misc ---- */
    'msg.added': '{name} اتضافت لطلبك',
    'msg.removed': '{name} اتشالت',
    'msg.cartEmpty': 'سلتك فاضية',
    'msg.orderPlaced': 'استلمنا طلبك — المطبخ بدأ فيه!',
    'msg.deliveryOff': 'التوصيل متوقف مؤقتًا — كلمنا وهناخد طلبك.',
    'msg.comingSoon': 'قريبًا',
  },
};
