-- Talabat-style discount engine v2
-- Adds independent free-delivery benefits, priority, and redemption history.
-- Applied to production separately after verification.
alter table public.discounts add column if not exists free_delivery boolean not null default false;
alter table public.discounts add column if not exists stackable boolean not null default false;
alter table public.discounts add column if not exists priority integer not null default 0;
create index if not exists idx_discounts_active_priority on public.discounts(active, priority desc, starts_at, expires_at);

create table if not exists public.discount_redemptions (
  id bigint generated by default as identity primary key,
  discount_id bigint not null references public.discounts(id) on delete restrict,
  order_id uuid not null references public.delivery_orders(id) on delete restrict,
  user_id uuid references auth.users(id) on delete set null,
  amount numeric(10,2) not null default 0,
  free_delivery boolean not null default false,
  created_at timestamptz not null default now(),
  unique(discount_id, order_id)
);
create index if not exists idx_discount_redemptions_user_discount
  on public.discount_redemptions(user_id, discount_id);
create index if not exists idx_discount_redemptions_discount
  on public.discount_redemptions(discount_id);

alter table public.discount_redemptions enable row level security;
revoke all on public.discount_redemptions from anon, authenticated;
grant select on public.discount_redemptions to authenticated;
create policy "discount_redemptions: admin read"
  on public.discount_redemptions for select to authenticated
  using ((select is_admin()));
