-- Aquarium Cafe full menu import: displayed prices include 14% VAT.
-- Generated from aquarium_menu.json. Existing products are archived, not deleted.
-- IMPORTANT: this migration intentionally does NOT modify Supabase Auth or RLS policies.

update public.categories set visible=false where slug not in ('breakfast', 'soup', 'salads', 'french-fries', 'appetizers', 'pastas', 'pizza', 'meat', 'chicken', 'sea-food', 'additions', 'kids-menu', 'additional-sides', 'fatta', 'melted-cheese-bowls', 'sandwiches', 'desserts-waffles', 'hot-drinks', 'cold-coffee-frappe', 'juices-mojitos', 'soft-drinks', 'shisha', 'smoothies-cocktails', 'milkshakes', 'special-hot-coffee');
update public.products set available=false where available=true;

insert into public.categories (name,name_ar,slug,sort_order,visible) values
  ('Breakfast', 'الفطار', 'breakfast', 10, true),
  ('Soup', 'الشوربة', 'soup', 20, true),
  ('Salads', 'السلطات', 'salads', 30, true),
  ('French Fries', 'البطاطس', 'french-fries', 40, true),
  ('Appetizers', 'المقبلات', 'appetizers', 50, true),
  ('Pastas', 'المكرونات', 'pastas', 60, true),
  ('Pizza', 'البيتزا', 'pizza', 70, true),
  ('Meat', 'اللحوم', 'meat', 80, true),
  ('Chicken', 'الفراخ', 'chicken', 90, true),
  ('Sea food', 'السي فود', 'sea-food', 100, true),
  ('Additions', 'الإضافات', 'additions', 110, true),
  ('Kids Menu', 'كيدز منيو', 'kids-menu', 120, true),
  ('Additional Sides', 'الأطباق الجانبية', 'additional-sides', 130, true),
  ('Fatta', 'الفتة', 'fatta', 140, true),
  ('Melted Cheese Bowls', 'طاسات الجبنة السايحة', 'melted-cheese-bowls', 150, true),
  ('Sandwiches', 'الساندوتشات', 'sandwiches', 160, true),
  ('Desserts & Waffles', 'الحلويات والوافل', 'desserts-waffles', 170, true),
  ('Hot Drinks', 'المشروبات الساخنة', 'hot-drinks', 180, true),
  ('Cold Coffee & Frappe', 'المشروبات الباردة والآيس كوفي', 'cold-coffee-frappe', 190, true),
  ('Juices & Mojitos', 'العصائر والموهيتو', 'juices-mojitos', 200, true),
  ('Soft Drinks', 'المشروبات الغازية والمياه', 'soft-drinks', 210, true),
  ('Shisha', 'الشيشة', 'shisha', 220, true),
  ('Smoothies & Cocktails', 'السموذي والكوكتيلات', 'smoothies-cocktails', 230, true),
  ('Milkshakes', 'ميلك شيك', 'milkshakes', 240, true),
  ('Special Hot Coffee', 'المشروبات الساخنة والقهوة', 'special-hot-coffee', 250, true)
on conflict (slug) do update set name=excluded.name, name_ar=excluded.name_ar, sort_order=excluded.sort_order, visible=true, updated_at=now();

-- Insert missing products. Source prices are multiplied by 1.14 and rounded to 2 decimals.
insert into public.products (category_id,name,name_ar,description,description_ar,price,image,badge,available,featured,sort_order)
select c.id, v.name, v.name_ar, v.description, v.description_ar, v.price, v.image, '', true, false, v.sort_order
from (values
  ('breakfast', 'Aquarium Breakfast', 'أكواريوم بريك فاست', '', 'أومليت + سوسيس + مكعبات بطاطس بالأعشاب + مشروم', 153.90, 'images/hero.webp', 10),
  ('breakfast', 'Oriental Breakfast', 'أورينتال بريك فاست', '', 'فول + فلافل + جبنه بالطماطم + أومليت', 125.40, 'images/hero.webp', 20),
  ('breakfast', 'Mix Cheese Breakfast', 'ميكس تشيز بريك فاست', '', 'جبنه مثلثات + رومي + شيدر + جبنه بيضاء', 153.90, 'images/hero.webp', 30),
  ('breakfast', 'Omelette', 'أومليت', '', '', 74.10, 'images/hero.webp', 40),
  ('breakfast', 'Omelette with pastirma', 'أومليت بسطرمه', '', '', 96.90, 'images/hero.webp', 50),
  ('breakfast', 'Spanish Omelette', 'اسبانش اومليت', '', '', 85.50, 'images/hero.webp', 60),
  ('breakfast', 'Omelette with Roumi Cheese', 'اومليت بالجبنة رومي', '', '', 91.20, 'images/hero.webp', 70),
  ('breakfast', 'Mashed Potatoes', 'بطاطس بوريه', '', '', 74.10, 'images/hero.webp', 80),
  ('breakfast', 'Beans', 'فول', '', '', 51.30, 'images/hero.webp', 90),
  ('breakfast', 'Falafel', 'فلافل', '', '', 51.30, 'images/hero.webp', 100),
  ('breakfast', 'Roumi cheese', 'جبنة رومي', '', '', 79.80, 'images/hero.webp', 110),
  ('breakfast', 'White cheese with Tomato', 'جبنة بالطماطم', '', '', 68.40, 'images/hero.webp', 120),
  ('soup', 'Chicken Mushroom cream soup', 'شوربة فراخ بالمشروم و الكريمة', '', '', 142.50, 'images/seafood.jpg', 130),
  ('soup', 'Chicken cream soup', 'شوربة فراخ بالكريمة', '', '', 125.40, 'images/seafood.jpg', 140),
  ('soup', 'Seafood soup', 'شوربة سي فود', '', '', 171.00, 'images/seafood.jpg', 150),
  ('soup', 'Shrimps soup', 'شوربة جمبري', '', '', 239.40, 'images/seafood.jpg', 160),
  ('soup', 'Mushroom soup', 'شوربة مشروم', '', '', 108.30, 'images/seafood.jpg', 170),
  ('soup', 'Tomato soup', 'شوربة طماطم', '', '', 91.20, 'images/seafood.jpg', 180),
  ('soup', 'Lentil soup', 'شوربة عدس', '', '', 96.90, 'images/seafood.jpg', 190),
  ('soup', 'Noodles Soup', 'شوربة لسان عصفور', '', '', 74.10, 'images/seafood.jpg', 200),
  ('soup', 'Vegetarian Soup', 'شوربة خضار', '', '', 79.80, 'images/seafood.jpg', 210),
  ('salads', 'Aquarium Salad', 'سلطة أكواريوم', '', 'قطع فراخ + ذرة حلوة + فاصوليا حمراء + خس + طماطم + فلفل ألوان + رومي', 193.80, 'images/seafood.jpg', 220),
  ('salads', 'Chicken Caesar Salad', 'سلطة سيزر بالفراخ', '', '', 182.40, 'images/seafood.jpg', 230),
  ('salads', 'Chicken with Pineapple and Avocado Salad', 'سلطه فراخ بالاناناس والافوكادو', '', 'شرائح فراخ + شرائح اناناس + شرائح افوكادو + جرجير + بصل', 205.20, 'images/seafood.jpg', 240),
  ('salads', 'Greek Salad', 'سلطة يوناني', '', '', 136.80, 'images/seafood.jpg', 250),
  ('salads', 'Tuna Salad', 'سلطة تونه', '', '', 205.20, 'images/seafood.jpg', 260),
  ('salads', 'Seafood Salad', 'سلطة سي فود', '', '', 222.30, 'images/seafood.jpg', 270),
  ('salads', 'Russian Salad', 'سلطه روسي', '', 'جزر + بسلة + بطاطس + مايونيز', 125.40, 'images/seafood.jpg', 280),
  ('salads', 'Red Beet with white cheese Salad', 'سلطة بنجر بالجبنة البيضاء', '', 'بنجر احمر + جبنة بيضاء', 114.00, 'images/seafood.jpg', 290),
  ('salads', 'Carrot with honey Salad', 'سلطة جزر بالعسل', '', 'جزر مسلوق + زنجبيل + زيت زيتون + عسل', 91.20, 'images/seafood.jpg', 300),
  ('salads', 'Caprese Salad', 'سلطة كابريزي', '', 'موزاريلا + ريحان + طماطم', 131.10, 'images/seafood.jpg', 310),
  ('salads', 'Tahini Salad', 'سلطة طحينه', '', '', 68.40, 'images/seafood.jpg', 320),
  ('salads', 'Baba Ghanoug Salad', 'سلطه بابا غنوج', '', '', 68.40, 'images/seafood.jpg', 330),
  ('salads', 'Garlic Salad', 'سلطة ثوميه', '', '', 68.40, 'images/seafood.jpg', 340),
  ('salads', 'Green Salad', 'سلطة خضراء', '', '', 68.40, 'images/seafood.jpg', 350),
  ('salads', 'Yogurt Salad', 'سلطة زبادي', '', '', 57.00, 'images/seafood.jpg', 360),
  ('salads', 'Coleslaw Salad', 'سلطة كولسلو', '', '', 74.10, 'images/seafood.jpg', 370),
  ('salads', 'Pickles', 'مخلل', '', '', 45.60, 'images/seafood.jpg', 380),
  ('french-fries', 'French Fries', 'فرايز', '', '', 68.40, 'images/placeholder.svg', 390),
  ('french-fries', 'Friskas Fries', 'فرسكاس', '', '', 79.80, 'images/placeholder.svg', 400),
  ('french-fries', 'Crocket Potatoes', 'بطاطس كروكيت', '', '', 96.90, 'images/placeholder.svg', 410),
  ('french-fries', 'French Fries with Cheddar Cheese', 'تشيز فرايز', '', '', 96.90, 'images/placeholder.svg', 420),
  ('french-fries', 'Cheese French Fries with Minced Meat', 'تشيز فرايز باللحمة', '', '', 136.80, 'images/placeholder.svg', 430),
  ('french-fries', 'Cheese French Fries with Chicken', 'تشيز فرايز بالفراخ', '', '', 136.80, 'images/placeholder.svg', 440),
  ('french-fries', 'Cheese French Fries with Sausage', 'تشيز فرايز بالسجق', '', '', 136.80, 'images/placeholder.svg', 450),
  ('appetizers', 'Aquarium Snacks', 'أكواريوم سناكس', '', 'جبنة مقلية + بصل مقلي سبرنج رول خضار + سمبوسك لحمة', 159.60, 'images/pizza.jpg', 460),
  ('appetizers', 'Fried Mozzarella Sticks', 'اصابع الموزاريلا المقلية', '', '', 142.50, 'images/pizza.jpg', 470),
  ('appetizers', 'Fried Onion Rings', 'حلقات البصل المقلية', '', '', 114.00, 'images/pizza.jpg', 480),
  ('appetizers', 'Chicken Strips', 'دجاج استريبس', '', '', 165.30, 'images/pizza.jpg', 490),
  ('appetizers', 'Chicken Fingers', 'اصابع الدجاج المقلية', '', '', 165.30, 'images/pizza.jpg', 500),
  ('appetizers', 'Chicken Wings', 'اجنحة الدجاج', '', '', 136.80, 'images/pizza.jpg', 510),
  ('appetizers', 'Chicken Sticks', 'تشيكن ستيكس', '', '', 165.30, 'images/pizza.jpg', 520),
  ('appetizers', 'Fried Calamari', 'كلماري مقلي', '', '', 182.40, 'images/pizza.jpg', 530),
  ('appetizers', 'Fried Shrimps', 'جمبري مقلي', '', '', 216.60, 'images/pizza.jpg', 540),
  ('appetizers', 'Fish Fingers', 'اصابع السمك المقلى', '', '', 148.20, 'images/pizza.jpg', 550),
  ('appetizers', 'Fish Kofta', 'كفتة سمك', '', '', 148.20, 'images/pizza.jpg', 560),
  ('appetizers', 'Sambousek with Meat', 'سمبوسك لحمه', '', '', 125.40, 'images/pizza.jpg', 570),
  ('appetizers', 'Sambousek with Cheese', 'سمبوسك جبنه', '', '', 102.60, 'images/pizza.jpg', 580),
  ('appetizers', 'Spring Rolls with vegetables', 'سبرنج رولز خضار', '', '', 102.60, 'images/pizza.jpg', 590),
  ('appetizers', 'Bruschetta', 'بروسكينا', '', '', 96.90, 'images/pizza.jpg', 600),
  ('appetizers', 'Garlic Bread', 'خبز محمص بصوص الثوم', '', '', 62.70, 'images/pizza.jpg', 610),
  ('pastas', 'Arrabiata', 'أرابيانا', '', 'اختيار المكرونة: بنا - أساجيتي - فيتوتشيني', 159.60, 'images/placeholder.svg', 620),
  ('pastas', 'pasta pesto chicken', 'باستا بستو فراخ', '', 'باستا مع فراخ وصوص البيستو', 210.90, 'images/placeholder.svg', 630),
  ('pastas', 'Pasta Mix cheese', 'باستا ميكس تشيز', '', 'باستا بصوص الكريمة مع موزاريلا وريكفورد وشيدر ورومي', 216.60, 'images/placeholder.svg', 640),
  ('pastas', 'Alfredo', 'ألفريدو', '', 'باستا مع فراخ بصوص الكريمة والمشروم', 216.60, 'images/placeholder.svg', 650),
  ('pastas', 'Chicken Crispy Pasta', 'باستا تشيكن كرسبي', '', 'باستا مع فراخ كرسبي والمشروم (صوص احمر او ابيض)', 228.00, 'images/placeholder.svg', 660),
  ('pastas', 'Negresco', 'نجرسكو', '', 'باستا مع فراخ بصوص الكريمة والمشروم والفلفل الاخضر والطماطم والموزاريلا', 239.40, 'images/placeholder.svg', 670),
  ('pastas', 'Beef fillet with cheese Pasta', 'فيلية تشيز باستا', '', 'باستا مع شرائح لحمة وجبنة شيدر (صوص احمر او ابيض)', 262.20, 'images/placeholder.svg', 680),
  ('pastas', 'Carbonara', 'كاربونارا', '', '', 239.40, 'images/placeholder.svg', 690),
  ('pastas', 'Bolognese', 'بولونيز', '', '', 228.00, 'images/placeholder.svg', 700),
  ('pastas', 'Meatball', 'ميت بول', '', '', 228.00, 'images/placeholder.svg', 710),
  ('pastas', 'Sausage Pasta', 'باستا سجق', '', '', 228.00, 'images/placeholder.svg', 720),
  ('pastas', 'Sausage Negresco', 'نجرسكو سجق', '', '', 245.10, 'images/placeholder.svg', 730),
  ('pastas', 'Tuna Pasta', 'باستا تونة', '', '', 228.00, 'images/placeholder.svg', 740),
  ('pastas', 'seafood', 'باستا سي فود', '', '(صوص احمر او ابيض)', 262.20, 'images/placeholder.svg', 750),
  ('pastas', 'Shrimp', 'باستا جمبري', '', '(صوص احمر او ابيض)', 319.20, 'images/placeholder.svg', 760),
  ('pastas', 'Shrimp Negresco', 'نجرسكو جمبري', '', '', 330.60, 'images/placeholder.svg', 770),
  ('pastas', 'Aquarium Pasta', 'باستا أكواريوم', '', 'فراخ - سلامي - سجق - هوت دوج - مشروم', 262.20, 'images/placeholder.svg', 780),
  ('pastas', 'Smoked salmon and caviar pasta', 'باستا سموك سلمون وكافيار', '', '(صوص احمر او ابيض)', 342.00, 'images/placeholder.svg', 790),
  ('pizza', 'Margherita', 'مارجريتا', '', '', 176.70, 'images/pizza.jpg', 800),
  ('pizza', 'Vegetables pizza', 'بيتزا خضروات', '', 'موزاريلا فلفل+ اخضر + فلفل الوان + طماطم + زيتون مشروم + بصل', 199.50, 'images/pizza.jpg', 810),
  ('pizza', 'Quattro formaggi pizza', 'بيتزا كواترو فورماجي', '', 'موزاريلا+رومي + ريكفورد+ شيدر', 222.30, 'images/pizza.jpg', 820),
  ('pizza', 'Chicken pizza', 'بيتزا فراخ', '', 'فراخ + موزاريلا + فلفل اخضر + طماطم + زيتون', 216.60, 'images/pizza.jpg', 830),
  ('pizza', 'Chicken Hawaiian pizza', 'بيتزا تشيكن هاواي', '', 'فراخ + شرائح الاناناس + موزاريلا', 228.00, 'images/pizza.jpg', 840),
  ('pizza', 'Chicken BBQ pizza', 'بيتزا تشيكن باربيكيو', '', 'فراخ + صوص باربيكيو + موزاريلا + فلفل اخضر + طماطم + زيتون', 228.00, 'images/pizza.jpg', 850),
  ('pizza', 'Chicken Crispy pizza', 'بيتزا تشيكن كرسبي', '', 'فراخ كرسبي + موزاريلا + فلفل اخضر + طماطم', 239.40, 'images/pizza.jpg', 860),
  ('pizza', 'Chicken Ranch pizza', 'بيتزا تشيكن رانش', '', 'فراخ + صوص رانش + موزاريلا + فلفل اخضر + زيتون', 228.00, 'images/pizza.jpg', 870),
  ('pizza', 'Chicken Tasty pizza', 'بيتزا تشيكن تيستي', '', 'فراخ+صوص تيستي+فلفل اخضر+طماطم+زيتون', 228.00, 'images/pizza.jpg', 880),
  ('pizza', 'Chicken Shawarma pizza', 'بيتزا شاورما فراخ', '', 'شاورما فراخ +فلفل اخضر+طماطم + بصل', 216.60, 'images/pizza.jpg', 890),
  ('pizza', 'Chicken Mix pizza', 'بيتزا مكس فراخ', '', 'فراخ مكس+موزاريلا+فلفل اخضر +طماطم+زيتون + تركي مدخن', 228.00, 'images/pizza.jpg', 900),
  ('pizza', 'Meat Shawarma pizza', 'بيتزا شاورما لحمة', '', 'شاورما لحمة+موزاريلا+فلفل اخضر +طماطم+ بصل', 250.80, 'images/pizza.jpg', 910),
  ('pizza', 'Minced Meat pizza', 'بيتزا لحمة', '', 'اللحم المفروم+موزاريلا+فلفل اخضر+طماطم+زيتون', 228.00, 'images/pizza.jpg', 920),
  ('pizza', 'Meatball pizza', 'بيتزا ميت بول', '', 'كرات اللحم المفروم + موزاريلا+ فلفل اخضر + طماطم + زيتون', 222.30, 'images/pizza.jpg', 930),
  ('pizza', 'Salami pizza', 'بيتزا سلامي', '', 'سلامي + موزاريلا + فلفل اخضر + طماطم + زيتون', 222.30, 'images/pizza.jpg', 940),
  ('pizza', 'Sausage pizza', 'بيتزا سجق', '', 'سجق + موزاريلا + فلفل اخضر + طماطم + زيتون', 222.30, 'images/pizza.jpg', 950),
  ('pizza', 'Pastirami pizza', 'بيتزا بسطرمة', '', 'بسطرمة + موزاريلا + فلفل اخضر + طماطم + زيتون', 250.80, 'images/pizza.jpg', 960),
  ('pizza', 'Hotdog pizza', 'بيتزا هوت دوج', '', 'هوت دوج + موزاريلا + فلفل اخضر + طماطم + زيتون', 216.60, 'images/pizza.jpg', 970),
  ('pizza', 'Tuna pizza', 'بيتزا تونه', '', 'تونة قطع + موزاريلا + فلفل اخضر + طماطم + زيتون', 239.40, 'images/pizza.jpg', 980),
  ('pizza', 'Seafood pizza', 'بيتزا سي فود', '', 'سمك + جمبري كاليماري + كابوريا اصابع + موزاريلا + فلفل اخضر+طماطم+ زيتون', 273.60, 'images/pizza.jpg', 990),
  ('pizza', 'Shrimp pizza', 'بيتزا جمبري', '', 'جمبري + موزاريلا + فلفل اخضر + طماطم + زيتون', 319.20, 'images/pizza.jpg', 1000),
  ('pizza', 'Smoked salmon and caviar pizza', 'بيتزا سموك سالمون كافيار', '', 'سلمون مدخن كافيار + كابوريا اصابع + موزاريلا + فلفل اخضر + زيتون', 336.30, 'images/pizza.jpg', 1010),
  ('pizza', 'Aquarium pizza', 'بيتزا أكواريوم', '', 'هوت دوج + سلامي + فراخ + سجق + موزاريلا + فلفل اخضر + طماطم+ زيتون', 285.00, 'images/pizza.jpg', 1020),
  ('pizza', 'Nutella with marshmallow pizza', 'بيتزا نوتيلا بالمارشيميلو', '', '', 199.50, 'images/pizza.jpg', 1030),
  ('meat', 'Grilled Steak Ribeye', 'استيك مشوي ريب أي', '', 'الأطباق تقدم مع صنفين اختيارية (فرايز - سوتيه - ارز - بوريه - مكرونة صوص ابيض/احمر)', 501.60, 'images/seafood.jpg', 1040),
  ('meat', 'Grilled Steak with pepper sauce Ribeye', 'استيك بيبور ريب أي', '', '', 513.00, 'images/seafood.jpg', 1050),
  ('meat', 'Grilled Steak with mushroom sauce Ribeye', 'استيك مشروم ريب أي', '', '', 547.20, 'images/seafood.jpg', 1060),
  ('meat', 'Grilled Beef Fillet', 'بيف فيليه مشوي', '', '', 433.20, 'images/seafood.jpg', 1070),
  ('meat', 'Grilled Beef Fillet with pepper sauce', 'بيف فيليه بيبور', '', '', 456.00, 'images/seafood.jpg', 1080),
  ('meat', 'Grilled Beef Fillet with mushroom sauce', 'بيف فيليه مشروم', '', '', 478.80, 'images/seafood.jpg', 1090),
  ('meat', 'Beef Asturganoff', 'بيف أسترجانوف', '', 'شرائح اللحم + فلفل ألوان + مشروم + براون صوص', 478.80, 'images/seafood.jpg', 1100),
  ('meat', 'Fajita Beef', 'فاهيتا لحمه', '', 'شرائح اللحم + فلفل ألوان + بصل', 456.00, 'images/seafood.jpg', 1110),
  ('meat', 'Chilli Beef', 'شيلي بيف', '', '', 478.80, 'images/seafood.jpg', 1120),
  ('meat', 'Piccata with mushroom sauce', 'بيكاتا مشروم', '', '', 478.80, 'images/seafood.jpg', 1130),
  ('meat', 'Escalope Pane', 'اسكالوب بانيه', '', '', 456.00, 'images/seafood.jpg', 1140),
  ('meat', 'Mix Grill', 'مكس جريل', '', 'كفته + شيش طاووق + كباب', 524.40, 'images/seafood.jpg', 1150),
  ('meat', 'Mushroom Meatballs', 'مشروم ميت بولز', '', '', 376.20, 'images/seafood.jpg', 1160),
  ('meat', 'kelo Kebab 1/3', '1/3 كيلو كباب', '', '', 547.20, 'images/seafood.jpg', 1170),
  ('meat', 'kelo Kofta 1/2', '1/2 كيلو كفته', '', '', 467.40, 'images/seafood.jpg', 1180),
  ('meat', 'Fajita mix Meat and Chicken', 'فاهيتا مكس لحمة وفراخ', '', '', 421.80, 'images/seafood.jpg', 1190),
  ('chicken', 'Grilled Chicken', 'جريلد تشيكن', '', 'صدور الدجاج المشوية مع التتبيلة الخاصة بنا', 353.40, 'images/seafood.jpg', 1200),
  ('chicken', 'Fajita Chicken', 'فاهيتا فراخ', '', '', 353.40, 'images/seafood.jpg', 1210),
  ('chicken', 'Half grilled boneless chicken', 'نصف فرخة مسحب', '', '', 364.80, 'images/seafood.jpg', 1220),
  ('chicken', 'Cordon Bleu', 'كوردن بلو', '', '', 364.80, 'images/seafood.jpg', 1230),
  ('chicken', 'Chicken Funji', 'تشيكن فونجي', '', 'قطع الدجاج مع صوص الكريمة والمشروم الفريش والفلفل الاخضر', 364.80, 'images/seafood.jpg', 1240),
  ('chicken', 'Chicken Piccata', 'بيكاتا فراخ', '', 'شرائح دجاج + مشروم براون صوص', 364.80, 'images/seafood.jpg', 1250),
  ('chicken', 'Chilli Chicken', 'شيلي تشيكن', '', '', 364.80, 'images/seafood.jpg', 1260),
  ('chicken', 'Chicken Kijon', 'تشيكن كيجون', '', '(صدور دجاج كرسبي-موزاريلا كريمي)', 364.80, 'images/seafood.jpg', 1270),
  ('chicken', 'Chicken Lemon', 'تشيكن ليمون', '', '(صدور دجاج مشوية مع وايت صوص بالليمون)', 364.80, 'images/seafood.jpg', 1280),
  ('chicken', 'Chicken Mushroom with Mozzarella', 'تشيكن مشروم و موزاريلا', '', 'صدور دجاج مقلية سلامي-موزاريلا-مشروم-فلفل الوان', 370.50, 'images/seafood.jpg', 1290),
  ('chicken', 'Chicken Crispy', 'تشيكن كرسبي', '', '', 370.50, 'images/seafood.jpg', 1300),
  ('chicken', 'Shish Tawook', 'شيش طاووق', '', '', 364.80, 'images/seafood.jpg', 1310),
  ('sea-food', 'Fish Fillet', 'سمك فيليه', '', 'مكلي او مشوي مع صوص كريمه وليامون', 319.20, 'images/placeholder.svg', 1320),
  ('sea-food', 'Mussels 250 gm', 'بلح البحر 250 جم', '', '', 330.60, 'images/placeholder.svg', 1330),
  ('sea-food', 'Calamari 250 gm', 'كاليماري 250 جم', '', 'مقلى او مشوى او ميكسيكان', 353.40, 'images/placeholder.svg', 1340),
  ('sea-food', 'Shrimps 250 gm', 'جمبري 250 جم', '', 'مقلى او مشوى او ميكسيكان', 501.60, 'images/placeholder.svg', 1350),
  ('sea-food', 'Mix Seafood', 'مكس سي فود', '', 'جمبري + كاليماري + سمك + بلح البحر', 478.80, 'images/placeholder.svg', 1360),
  ('sea-food', 'Salmon Kebab', 'سلمون كباب', '', 'قطع السلمون المشوي بطريقة الكباب مع صوص التارتار', 604.20, 'images/placeholder.svg', 1370),
  ('sea-food', 'Grilled Salmon Steak', 'سلمون مشوي', '', 'شريحة السلمون المشوية مع صوص كريمة', 615.60, 'images/placeholder.svg', 1380),
  ('additions', 'Chicken', 'فراخ', '', '', 74.10, 'images/placeholder.svg', 1390),
  ('additions', 'Minces Meat', 'لحمة مفرومة', '', '', 68.40, 'images/placeholder.svg', 1400),
  ('additions', 'Sausage', 'سجق', '', '', 74.10, 'images/placeholder.svg', 1410),
  ('additions', 'Pastirami', 'بسطرمة', '', '', 79.80, 'images/placeholder.svg', 1420),
  ('additions', 'Salami', 'سلامي', '', '', 74.10, 'images/placeholder.svg', 1430),
  ('additions', 'Hotdog', 'هوت دوج', '', '', 68.40, 'images/placeholder.svg', 1440),
  ('additions', 'Tuna', 'تونة', '', '', 91.20, 'images/placeholder.svg', 1450),
  ('additions', 'Shrimps', 'جمبري', '', '', 114.00, 'images/placeholder.svg', 1460),
  ('additions', 'Calamari', 'كاليماري', '', '', 102.60, 'images/placeholder.svg', 1470),
  ('additions', 'Fish Fillet', 'سمك فيليه', '', '', 91.20, 'images/placeholder.svg', 1480),
  ('additions', 'Crab Stick', 'كابوريا اصابع', '', '', 342.00, 'images/placeholder.svg', 1490),
  ('additions', 'Caviar', 'كافيار', '', '', 74.10, 'images/placeholder.svg', 1500),
  ('additions', 'Olives', 'زيتون', '', '', 45.60, 'images/placeholder.svg', 1510),
  ('additions', 'Vegetables', 'خضروات', '', '', 45.60, 'images/placeholder.svg', 1520),
  ('additions', 'Mushroom', 'مشروم', '', '', 57.00, 'images/placeholder.svg', 1530),
  ('additions', 'jalapeno', 'هالابينو', '', '', 34.20, 'images/placeholder.svg', 1540),
  ('additions', 'Mozzarella Cheese', 'موزاريلا', '', '', 85.50, 'images/placeholder.svg', 1550),
  ('additions', 'Roumi cheese', 'رومي', '', '', 62.70, 'images/placeholder.svg', 1560),
  ('additions', 'Cheddar Cheese', 'شيدر', '', '', 68.40, 'images/placeholder.svg', 1570),
  ('additions', 'Blue Cheese', 'ريكفورد', '', '', 79.80, 'images/placeholder.svg', 1580),
  ('kids-menu', 'Dodo Meal', 'وجبه دودو', '', 'اونيون رينج و استربس موزاريلا مقلية و بطاطس فرسكاس', 182.40, 'images/placeholder.svg', 1590),
  ('additional-sides', 'White Rice', 'ارز ابيض', '', '', 68.40, 'images/placeholder.svg', 1600),
  ('additional-sides', 'White Rice with Vermicelli', 'ارز بالشعرية', '', '', 74.10, 'images/placeholder.svg', 1610),
  ('additional-sides', 'Brown Rice', 'ارز صيادية', '', '', 79.80, 'images/placeholder.svg', 1620),
  ('additional-sides', 'Basmati Rice', 'ارز بسمتي', '', '', 114.00, 'images/placeholder.svg', 1630),
  ('additional-sides', 'Mexican rice', 'ارز مكسيكي', '', '', 114.00, 'images/placeholder.svg', 1640),
  ('additional-sides', 'Sauteed Vegetables', 'خضار سوتيه', '', '', 74.10, 'images/placeholder.svg', 1650),
  ('additional-sides', 'Mashed Potatoes', 'بطاطس بوريه', '', '', 68.40, 'images/placeholder.svg', 1660),
  ('additional-sides', 'Red Sauce Pasta', 'باستا ريد صوص', '', '', 102.60, 'images/placeholder.svg', 1670),
  ('additional-sides', 'White Sauce Pasta', 'باستا وايت صوص', '', '', 119.70, 'images/placeholder.svg', 1680),
  ('fatta', 'Oriental Fattat', 'فته شرقي', '', '', 330.60, 'images/placeholder.svg', 1690),
  ('fatta', 'Fattet Chicken Shawarma', 'فته شاورما فراخ', '', '', 216.60, 'images/placeholder.svg', 1700),
  ('fatta', 'Fattet Meat shawarma', 'فته شاورما لحمه', '', '', 228.00, 'images/placeholder.svg', 1710),
  ('fatta', 'Fattet Shawarma Mix', 'فته شاورما مكس', '', '', 216.60, 'images/placeholder.svg', 1720),
  ('melted-cheese-bowls', 'Shish Tawook', 'شيش طاووق', '', '', 210.90, 'images/placeholder.svg', 1730),
  ('melted-cheese-bowls', 'Strips', 'استريبس', '', '', 216.60, 'images/placeholder.svg', 1740),
  ('melted-cheese-bowls', 'Zinger', 'زنجر', '', '', 216.60, 'images/placeholder.svg', 1750),
  ('melted-cheese-bowls', 'Cordon Bleu', 'كوردن بلو', '', '', 239.40, 'images/placeholder.svg', 1760),
  ('melted-cheese-bowls', 'Chicken Crispy', 'تشيكن كرسبي', '', '', 216.60, 'images/placeholder.svg', 1770),
  ('melted-cheese-bowls', 'Sausage', 'سجق', '', '', 216.60, 'images/placeholder.svg', 1780),
  ('melted-cheese-bowls', 'Kofta', 'كفتة', '', '', 205.20, 'images/placeholder.svg', 1790),
  ('melted-cheese-bowls', 'Pastirma', 'بسطرمة', '', '', 228.00, 'images/placeholder.svg', 1800),
  ('melted-cheese-bowls', 'Salami', 'سلامي', '', '', 216.60, 'images/placeholder.svg', 1810),
  ('melted-cheese-bowls', 'Hotdog', 'هوت دوج', '', '', 205.20, 'images/placeholder.svg', 1820),
  ('melted-cheese-bowls', 'Shrimps', 'جمبري', '', '', 250.80, 'images/placeholder.svg', 1830),
  ('melted-cheese-bowls', 'Calamari', 'كاليماري', '', '', 239.40, 'images/placeholder.svg', 1840),
  ('sandwiches', 'Chicken Crispy', 'تشيكن كرسبي', '', 'ساندوتش دجاج كرسبي مع الخس والمايونيز', 148.20, 'images/hero-sea.jpg', 1850),
  ('sandwiches', 'Chicken Pane', 'تشيكن بانيه', '', '', 142.50, 'images/hero-sea.jpg', 1860),
  ('sandwiches', 'Shish Tawook Sandwich', 'شيش طاووق', '', '', 148.20, 'images/hero-sea.jpg', 1870),
  ('sandwiches', 'Zinger', 'زنجر', '', '', 153.90, 'images/hero-sea.jpg', 1880),
  ('sandwiches', 'Chicken Fajita Sandwich', 'فاهيتا فراخ', '', '', 153.90, 'images/hero-sea.jpg', 1890),
  ('sandwiches', 'Chicken Shawarma Sandwich', 'شاورما فراخ', '', '', 148.20, 'images/hero-sea.jpg', 1900),
  ('sandwiches', 'Cordon Bleu Sandwich', 'كوردن بلو', '', '', 165.30, 'images/hero-sea.jpg', 1910),
  ('sandwiches', 'Beef Fajita Sandwich', 'فاهيتا لحم', '', '', 176.70, 'images/hero-sea.jpg', 1920),
  ('sandwiches', 'Beef Shawarma Sandwich', 'شاورما لحم', '', '', 171.00, 'images/hero-sea.jpg', 1930),
  ('sandwiches', 'Kofta Sandwich', 'كفتة', '', '', 148.20, 'images/hero-sea.jpg', 1940),
  ('sandwiches', 'Classic Beef Burger', 'برجر لحم كلاسيك', '', '', 159.60, 'images/hero-sea.jpg', 1950),
  ('sandwiches', 'Cheese Burger', 'تشيز برجر', '', '', 176.70, 'images/hero-sea.jpg', 1960),
  ('sandwiches', 'Mushroom Burger', 'مشروم برجر', '', '', 188.10, 'images/hero-sea.jpg', 1970),
  ('sandwiches', 'Aquarium Burger', 'أكواريوم برجر', '', 'برجر لحم + بيض + جبنة شيدر + بصل كرمل', 205.20, 'images/hero-sea.jpg', 1980),
  ('sandwiches', 'Fried Shrimp Sandwich', 'جمبري مقلي', '', '', 205.20, 'images/hero-sea.jpg', 1990),
  ('sandwiches', 'Fried Fish Fillet Sandwich', 'سمك فيليه مقلي', '', '', 159.60, 'images/hero-sea.jpg', 2000),
  ('sandwiches', 'Fried Calamari Sandwich', 'كاليماري مقلي', '', '', 171.00, 'images/hero-sea.jpg', 2010),
  ('sandwiches', 'Tuna Sandwich', 'ساندوتش تونة', '', '', 136.80, 'images/hero-sea.jpg', 2020),
  ('sandwiches', 'Club Sandwich', 'كلوب ساندوتش', '', 'توست + فراخ + بيض + جبنة + سلامي', 171.00, 'images/hero-sea.jpg', 2030),
  ('desserts-waffles', 'Nutella Waffle', 'وافل نوتيلا', '', '', 108.30, 'images/placeholder.svg', 2040),
  ('desserts-waffles', 'Lotus Waffle', 'وافل لوتس', '', '', 125.40, 'images/placeholder.svg', 2050),
  ('desserts-waffles', 'Fruit Waffle', 'وافل فواكه', '', '', 125.40, 'images/placeholder.svg', 2060),
  ('desserts-waffles', 'Mix Sauce Waffle', 'وافل ميكس صوص', '', '', 131.10, 'images/placeholder.svg', 2070),
  ('desserts-waffles', 'Nutella Crepe', 'كريب نوتيلا', '', '', 102.60, 'images/placeholder.svg', 2080),
  ('desserts-waffles', 'Banana Nutella Crepe', 'كريب موز ونوتيلا', '', '', 114.00, 'images/placeholder.svg', 2090),
  ('desserts-waffles', 'Lotus Crepe', 'كريب لوتس', '', '', 119.70, 'images/placeholder.svg', 2100),
  ('desserts-waffles', 'Molten Cake', 'مولتن كيك', '', 'يقدم مع بولة أيس كريم', 125.40, 'images/placeholder.svg', 2110),
  ('desserts-waffles', 'Cheesecake', 'تشيز كيك', '', 'توت / فراولة / لوتس', 108.30, 'images/placeholder.svg', 2120),
  ('desserts-waffles', 'Sweet Omelette / Pancake', 'أومليت حلو', '', '', 96.90, 'images/placeholder.svg', 2130),
  ('desserts-waffles', 'Om Ali with Nuts', 'أم علي بالمكسرات', '', '', 85.50, 'images/placeholder.svg', 2140),
  ('desserts-waffles', 'Ice Cream Scoop', 'بولة أيس كريم', '', '', 34.20, 'images/placeholder.svg', 2150),
  ('hot-drinks', 'Single Espresso', 'إسبرسو سينجل', '', '', 45.60, 'images/espresso.webp', 2160),
  ('hot-drinks', 'Double Espresso', 'إسبرسو دبل', '', '', 57.00, 'images/espresso.webp', 2170),
  ('hot-drinks', 'Americano', 'أمريكانو', '', '', 62.70, 'images/espresso.webp', 2180),
  ('hot-drinks', 'Cappuccino', 'كابتشينو', '', '', 74.10, 'images/espresso.webp', 2190),
  ('hot-drinks', 'Cafe Latte', 'لاتيه', '', '', 74.10, 'images/espresso.webp', 2200),
  ('hot-drinks', 'Flat White', 'فلاد وايت', '', '', 79.80, 'images/espresso.webp', 2210),
  ('hot-drinks', 'Hot Mocha', 'موكا ساخنة', '', '', 85.50, 'images/espresso.webp', 2220),
  ('hot-drinks', 'Hot Chocolate', 'هوت شوكولاتة', '', '', 79.80, 'images/espresso.webp', 2230),
  ('hot-drinks', 'Plain Sahlab', 'سحلب سادة', '', '', 62.70, 'images/espresso.webp', 2240),
  ('hot-drinks', 'Sahlab with Nuts', 'سحلب بالمكسرات', '', '', 79.80, 'images/espresso.webp', 2250),
  ('hot-drinks', 'Tea', 'شاي فتلة', '', '', 34.20, 'images/espresso.webp', 2260),
  ('hot-drinks', 'Tea with Mint', 'شاي بالنعناع / أوراق الشاي', '', '', 39.90, 'images/espresso.webp', 2270),
  ('hot-drinks', 'Herbal Tea', 'أعشاب طبيعية', '', 'ينسون - كركديه - نعناع - قرفة', 39.90, 'images/espresso.webp', 2280),
  ('hot-drinks', 'Turkish Coffee Single', 'قهوة تركي سينجل', '', '', 39.90, 'images/espresso.webp', 2290),
  ('hot-drinks', 'Turkish Coffee Double', 'قهوة تركي دبل', '', '', 51.30, 'images/espresso.webp', 2300),
  ('hot-drinks', 'French Coffee', 'قهوة فرنساوي', '', '', 57.00, 'images/espresso.webp', 2310),
  ('hot-drinks', 'Hazelnut Coffee', 'قهوة بندق', '', '', 62.70, 'images/espresso.webp', 2320),
  ('cold-coffee-frappe', 'Iced Latte', 'آيس لاتيه', '', '', 79.80, 'images/placeholder.svg', 2330),
  ('cold-coffee-frappe', 'Iced Mocha', 'آيس موكا', '', '', 85.50, 'images/placeholder.svg', 2340),
  ('cold-coffee-frappe', 'Iced Americano', 'آيس أمريكانو', '', '', 68.40, 'images/placeholder.svg', 2350),
  ('cold-coffee-frappe', 'Vanilla Frappe', 'فرابيه فانيليا', '', '', 85.50, 'images/placeholder.svg', 2360),
  ('cold-coffee-frappe', 'Chocolate Frappe', 'فرابيه شوكولاتة', '', '', 85.50, 'images/placeholder.svg', 2370),
  ('cold-coffee-frappe', 'Caramel Frappe', 'فرابيه كراميل', '', '', 85.50, 'images/placeholder.svg', 2380),
  ('cold-coffee-frappe', 'Lotus Frappe', 'فرابيه لوتس', '', '', 96.90, 'images/placeholder.svg', 2390),
  ('juices-mojitos', 'Fresh Orange', 'عصير برتقال طازج', '', '', 57.00, 'images/placeholder.svg', 2400),
  ('juices-mojitos', 'Mango Juice', 'عصير مانجو', '', '', 68.40, 'images/placeholder.svg', 2410),
  ('juices-mojitos', 'Guava Juice', 'عصير جوافة', '', '', 57.00, 'images/placeholder.svg', 2420),
  ('juices-mojitos', 'Strawberry Juice', 'عصير فراولة', '', '', 57.00, 'images/placeholder.svg', 2430),
  ('juices-mojitos', 'Lemon Mint', 'عصير ليمون نعناع', '', '', 57.00, 'images/placeholder.svg', 2440),
  ('juices-mojitos', 'Banana Milkshake', 'عصير موز بالحليب', '', '', 62.70, 'images/placeholder.svg', 2450),
  ('juices-mojitos', 'Classic Mojito', 'موهيتو كلاسيك', '', '', 74.10, 'images/placeholder.svg', 2460),
  ('juices-mojitos', 'Blueberry Mojito', 'موهيتو بلوبيري', '', '', 79.80, 'images/placeholder.svg', 2470),
  ('juices-mojitos', 'Strawberry Mojito', 'موهيتو فراولة', '', '', 79.80, 'images/placeholder.svg', 2480),
  ('juices-mojitos', 'Special Cocktail', 'مكس العصائر الخاصة', '', '', 85.50, 'images/placeholder.svg', 2490),
  ('soft-drinks', 'Small Water', 'مياه معدنية صغيرة', '', '', 22.80, 'images/placeholder.svg', 2500),
  ('soft-drinks', 'Large Water', 'مياه معدنية كبيرة', '', '', 34.20, 'images/placeholder.svg', 2510),
  ('soft-drinks', 'Canned Soda', 'كانز كولا / سبرايت / فانتا', '', '', 39.90, 'images/placeholder.svg', 2520),
  ('soft-drinks', 'Energy Drink', 'مشروب طاقة', '', '', 74.10, 'images/placeholder.svg', 2530),
  ('soft-drinks', 'Schweppes', 'شويبس ذهبي / رومان', '', '', 45.60, 'images/placeholder.svg', 2540),
  ('soft-drinks', 'Birell / Fayrouz', 'بيريل / فيروز', '', '', 45.60, 'images/placeholder.svg', 2550),
  ('shisha', 'Traditional Shisha', 'شيشة قص / سلوم', '', '', 45.60, 'images/shisha.jpg', 2560),
  ('shisha', 'Two Apples Shisha', 'شيشة تفاحتين فاخر', '', '', 85.50, 'images/shisha.jpg', 2570),
  ('shisha', 'Flavored Shisha', 'شيشة خوخ / خلطات نكهات', '', '', 85.50, 'images/shisha.jpg', 2580),
  ('shisha', 'Aquarium Special Shisha', 'شيشة أكواريوم سبيشال', '', '', 108.30, 'images/shisha.jpg', 2590),
  ('shisha', 'Change Head Two Apples', 'تغيير حجر تفاحتين', '', '', 51.30, 'images/shisha.jpg', 2600),
  ('shisha', 'Change Head Flavor', 'تغيير حجر نكهة', '', '', 51.30, 'images/shisha.jpg', 2610),
  ('shisha', 'Hygienic Hose', 'لي طبي / هوز صحي', '', '', 17.10, 'images/shisha.jpg', 2620),
  ('smoothies-cocktails', 'Mango Smoothie', 'سموذي مانجو', '', '', 79.80, 'images/placeholder.svg', 2630),
  ('smoothies-cocktails', 'Strawberry Smoothie', 'سموذي فراولة', '', '', 74.10, 'images/placeholder.svg', 2640),
  ('smoothies-cocktails', 'Lemon Mint Smoothie', 'سموذي ليمون نعناع', '', '', 74.10, 'images/placeholder.svg', 2650),
  ('smoothies-cocktails', 'Watermelon Smoothie', 'سموذي بطيخ', '', '', 74.10, 'images/placeholder.svg', 2660),
  ('smoothies-cocktails', 'Blueberry Smoothie', 'سموذي بلوبيري', '', '', 85.50, 'images/placeholder.svg', 2670),
  ('smoothies-cocktails', 'Peach Smoothie', 'سموذي خوخ', '', '', 79.80, 'images/placeholder.svg', 2680),
  ('smoothies-cocktails', 'Bubble Gum Smoothie', 'سموذي بوبل جام', '', '', 79.80, 'images/placeholder.svg', 2690),
  ('smoothies-cocktails', 'Florida Cocktail', 'كوكتيل فلوريدا', '', 'مانجو + فراولة + جوافة + أيس كريم', 91.20, 'images/placeholder.svg', 2700),
  ('smoothies-cocktails', 'Aquarium Special Cocktail Mix', 'كوكتيل أكواريوم المتميز', '', 'خلطة الفواكه الطازجة مع قطع المكسرات والعسل', 102.60, 'images/placeholder.svg', 2710),
  ('smoothies-cocktails', 'Pina Colada', 'بينا كولادا', '', 'أناناس + جوز هند + حليب', 91.20, 'images/placeholder.svg', 2720),
  ('smoothies-cocktails', 'Sunrise Cocktail', 'صن رايز', '', 'برتقال + رمان + سيروب مميز', 79.80, 'images/placeholder.svg', 2730),
  ('milkshakes', 'Vanilla Milkshake', 'ميلك شيك فانيليا', '', '', 85.50, 'images/placeholder.svg', 2740),
  ('milkshakes', 'Chocolate Milkshake', 'ميلك شيك شوكولاتة', '', '', 85.50, 'images/placeholder.svg', 2750),
  ('milkshakes', 'Strawberry Milkshake', 'ميلك شيك فراولة', '', '', 85.50, 'images/placeholder.svg', 2760),
  ('milkshakes', 'Mango Milkshake', 'ميلك شيك مانجو', '', '', 91.20, 'images/placeholder.svg', 2770),
  ('milkshakes', 'Oreo Milkshake', 'ميلك شيك أوريو', '', '', 96.90, 'images/placeholder.svg', 2780),
  ('milkshakes', 'Lotus Milkshake', 'ميلك شيك لوتس', '', '', 102.60, 'images/placeholder.svg', 2790),
  ('milkshakes', 'Nutella Milkshake', 'ميلك شيك نوتيلا', '', '', 102.60, 'images/placeholder.svg', 2800),
  ('milkshakes', 'Caramel Milkshake', 'ميلك شيك كراميل', '', '', 91.20, 'images/placeholder.svg', 2810),
  ('special-hot-coffee', 'Espresso Macchiato', 'إسبرسو مكياتو', '', '', 62.70, 'images/placeholder.svg', 2820),
  ('special-hot-coffee', 'Cortado', 'كورتادو', '', '', 74.10, 'images/placeholder.svg', 2830),
  ('special-hot-coffee', 'Caramel Coffee', 'قهوة بالكراميل', '', '', 79.80, 'images/placeholder.svg', 2840),
  ('special-hot-coffee', 'Vanilla Coffee', 'قهوة بالفانيليا', '', '', 79.80, 'images/placeholder.svg', 2850),
  ('special-hot-coffee', 'Arabic Coffee / Dallah', 'قهوة عربية', '', '', 85.50, 'images/placeholder.svg', 2860),
  ('special-hot-coffee', 'Hot Cider', 'هوت سيدار / تفاح بالسينامون', '', 'عصير تفاح ساخن مع القرفة', 74.10, 'images/placeholder.svg', 2870),
  ('special-hot-coffee', 'Warm Milk with Honey', 'حليب دافئ بالعسل', '', '', 51.30, 'images/placeholder.svg', 2880)
) as v(category_slug,name,name_ar,description,description_ar,price,image,sort_order)
join public.categories c on c.slug=v.category_slug
where not exists (select 1 from public.products p where p.category_id=c.id and p.name=v.name and p.name_ar=v.name_ar);

-- Re-enable products that belong to the new menu.
update public.products p set available=true, updated_at=now() where exists (select 1 from public.categories c where c.id=p.category_id and c.slug in ('breakfast', 'soup', 'salads', 'french-fries', 'appetizers', 'pastas', 'pizza', 'meat', 'chicken', 'sea-food', 'additions', 'kids-menu', 'additional-sides', 'fatta', 'melted-cheese-bowls', 'sandwiches', 'desserts-waffles', 'hot-drinks', 'cold-coffee-frappe', 'juices-mojitos', 'soft-drinks', 'shisha', 'smoothies-cocktails', 'milkshakes', 'special-hot-coffee')) and exists (select 1 from (values
('breakfast', 'Aquarium Breakfast', 'أكواريوم بريك فاست'),
('breakfast', 'Oriental Breakfast', 'أورينتال بريك فاست'),
('breakfast', 'Mix Cheese Breakfast', 'ميكس تشيز بريك فاست'),
('breakfast', 'Omelette', 'أومليت'),
('breakfast', 'Omelette with pastirma', 'أومليت بسطرمه'),
('breakfast', 'Spanish Omelette', 'اسبانش اومليت'),
('breakfast', 'Omelette with Roumi Cheese', 'اومليت بالجبنة رومي'),
('breakfast', 'Mashed Potatoes', 'بطاطس بوريه'),
('breakfast', 'Beans', 'فول'),
('breakfast', 'Falafel', 'فلافل'),
('breakfast', 'Roumi cheese', 'جبنة رومي'),
('breakfast', 'White cheese with Tomato', 'جبنة بالطماطم'),
('soup', 'Chicken Mushroom cream soup', 'شوربة فراخ بالمشروم و الكريمة'),
('soup', 'Chicken cream soup', 'شوربة فراخ بالكريمة'),
('soup', 'Seafood soup', 'شوربة سي فود'),
('soup', 'Shrimps soup', 'شوربة جمبري'),
('soup', 'Mushroom soup', 'شوربة مشروم'),
('soup', 'Tomato soup', 'شوربة طماطم'),
('soup', 'Lentil soup', 'شوربة عدس'),
('soup', 'Noodles Soup', 'شوربة لسان عصفور'),
('soup', 'Vegetarian Soup', 'شوربة خضار'),
('salads', 'Aquarium Salad', 'سلطة أكواريوم'),
('salads', 'Chicken Caesar Salad', 'سلطة سيزر بالفراخ'),
('salads', 'Chicken with Pineapple and Avocado Salad', 'سلطه فراخ بالاناناس والافوكادو'),
('salads', 'Greek Salad', 'سلطة يوناني'),
('salads', 'Tuna Salad', 'سلطة تونه'),
('salads', 'Seafood Salad', 'سلطة سي فود'),
('salads', 'Russian Salad', 'سلطه روسي'),
('salads', 'Red Beet with white cheese Salad', 'سلطة بنجر بالجبنة البيضاء'),
('salads', 'Carrot with honey Salad', 'سلطة جزر بالعسل'),
('salads', 'Caprese Salad', 'سلطة كابريزي'),
('salads', 'Tahini Salad', 'سلطة طحينه'),
('salads', 'Baba Ghanoug Salad', 'سلطه بابا غنوج'),
('salads', 'Garlic Salad', 'سلطة ثوميه'),
('salads', 'Green Salad', 'سلطة خضراء'),
('salads', 'Yogurt Salad', 'سلطة زبادي'),
('salads', 'Coleslaw Salad', 'سلطة كولسلو'),
('salads', 'Pickles', 'مخلل'),
('french-fries', 'French Fries', 'فرايز'),
('french-fries', 'Friskas Fries', 'فرسكاس'),
('french-fries', 'Crocket Potatoes', 'بطاطس كروكيت'),
('french-fries', 'French Fries with Cheddar Cheese', 'تشيز فرايز'),
('french-fries', 'Cheese French Fries with Minced Meat', 'تشيز فرايز باللحمة'),
('french-fries', 'Cheese French Fries with Chicken', 'تشيز فرايز بالفراخ'),
('french-fries', 'Cheese French Fries with Sausage', 'تشيز فرايز بالسجق'),
('appetizers', 'Aquarium Snacks', 'أكواريوم سناكس'),
('appetizers', 'Fried Mozzarella Sticks', 'اصابع الموزاريلا المقلية'),
('appetizers', 'Fried Onion Rings', 'حلقات البصل المقلية'),
('appetizers', 'Chicken Strips', 'دجاج استريبس'),
('appetizers', 'Chicken Fingers', 'اصابع الدجاج المقلية'),
('appetizers', 'Chicken Wings', 'اجنحة الدجاج'),
('appetizers', 'Chicken Sticks', 'تشيكن ستيكس'),
('appetizers', 'Fried Calamari', 'كلماري مقلي'),
('appetizers', 'Fried Shrimps', 'جمبري مقلي'),
('appetizers', 'Fish Fingers', 'اصابع السمك المقلى'),
('appetizers', 'Fish Kofta', 'كفتة سمك'),
('appetizers', 'Sambousek with Meat', 'سمبوسك لحمه'),
('appetizers', 'Sambousek with Cheese', 'سمبوسك جبنه'),
('appetizers', 'Spring Rolls with vegetables', 'سبرنج رولز خضار'),
('appetizers', 'Bruschetta', 'بروسكينا'),
('appetizers', 'Garlic Bread', 'خبز محمص بصوص الثوم'),
('pastas', 'Arrabiata', 'أرابيانا'),
('pastas', 'pasta pesto chicken', 'باستا بستو فراخ'),
('pastas', 'Pasta Mix cheese', 'باستا ميكس تشيز'),
('pastas', 'Alfredo', 'ألفريدو'),
('pastas', 'Chicken Crispy Pasta', 'باستا تشيكن كرسبي'),
('pastas', 'Negresco', 'نجرسكو'),
('pastas', 'Beef fillet with cheese Pasta', 'فيلية تشيز باستا'),
('pastas', 'Carbonara', 'كاربونارا'),
('pastas', 'Bolognese', 'بولونيز'),
('pastas', 'Meatball', 'ميت بول'),
('pastas', 'Sausage Pasta', 'باستا سجق'),
('pastas', 'Sausage Negresco', 'نجرسكو سجق'),
('pastas', 'Tuna Pasta', 'باستا تونة'),
('pastas', 'seafood', 'باستا سي فود'),
('pastas', 'Shrimp', 'باستا جمبري'),
('pastas', 'Shrimp Negresco', 'نجرسكو جمبري'),
('pastas', 'Aquarium Pasta', 'باستا أكواريوم'),
('pastas', 'Smoked salmon and caviar pasta', 'باستا سموك سلمون وكافيار'),
('pizza', 'Margherita', 'مارجريتا'),
('pizza', 'Vegetables pizza', 'بيتزا خضروات'),
('pizza', 'Quattro formaggi pizza', 'بيتزا كواترو فورماجي'),
('pizza', 'Chicken pizza', 'بيتزا فراخ'),
('pizza', 'Chicken Hawaiian pizza', 'بيتزا تشيكن هاواي'),
('pizza', 'Chicken BBQ pizza', 'بيتزا تشيكن باربيكيو'),
('pizza', 'Chicken Crispy pizza', 'بيتزا تشيكن كرسبي'),
('pizza', 'Chicken Ranch pizza', 'بيتزا تشيكن رانش'),
('pizza', 'Chicken Tasty pizza', 'بيتزا تشيكن تيستي'),
('pizza', 'Chicken Shawarma pizza', 'بيتزا شاورما فراخ'),
('pizza', 'Chicken Mix pizza', 'بيتزا مكس فراخ'),
('pizza', 'Meat Shawarma pizza', 'بيتزا شاورما لحمة'),
('pizza', 'Minced Meat pizza', 'بيتزا لحمة'),
('pizza', 'Meatball pizza', 'بيتزا ميت بول'),
('pizza', 'Salami pizza', 'بيتزا سلامي'),
('pizza', 'Sausage pizza', 'بيتزا سجق'),
('pizza', 'Pastirami pizza', 'بيتزا بسطرمة'),
('pizza', 'Hotdog pizza', 'بيتزا هوت دوج'),
('pizza', 'Tuna pizza', 'بيتزا تونه'),
('pizza', 'Seafood pizza', 'بيتزا سي فود'),
('pizza', 'Shrimp pizza', 'بيتزا جمبري'),
('pizza', 'Smoked salmon and caviar pizza', 'بيتزا سموك سالمون كافيار'),
('pizza', 'Aquarium pizza', 'بيتزا أكواريوم'),
('pizza', 'Nutella with marshmallow pizza', 'بيتزا نوتيلا بالمارشيميلو'),
('meat', 'Grilled Steak Ribeye', 'استيك مشوي ريب أي'),
('meat', 'Grilled Steak with pepper sauce Ribeye', 'استيك بيبور ريب أي'),
('meat', 'Grilled Steak with mushroom sauce Ribeye', 'استيك مشروم ريب أي'),
('meat', 'Grilled Beef Fillet', 'بيف فيليه مشوي'),
('meat', 'Grilled Beef Fillet with pepper sauce', 'بيف فيليه بيبور'),
('meat', 'Grilled Beef Fillet with mushroom sauce', 'بيف فيليه مشروم'),
('meat', 'Beef Asturganoff', 'بيف أسترجانوف'),
('meat', 'Fajita Beef', 'فاهيتا لحمه'),
('meat', 'Chilli Beef', 'شيلي بيف'),
('meat', 'Piccata with mushroom sauce', 'بيكاتا مشروم'),
('meat', 'Escalope Pane', 'اسكالوب بانيه'),
('meat', 'Mix Grill', 'مكس جريل'),
('meat', 'Mushroom Meatballs', 'مشروم ميت بولز'),
('meat', 'kelo Kebab 1/3', '1/3 كيلو كباب'),
('meat', 'kelo Kofta 1/2', '1/2 كيلو كفته'),
('meat', 'Fajita mix Meat and Chicken', 'فاهيتا مكس لحمة وفراخ'),
('chicken', 'Grilled Chicken', 'جريلد تشيكن'),
('chicken', 'Fajita Chicken', 'فاهيتا فراخ'),
('chicken', 'Half grilled boneless chicken', 'نصف فرخة مسحب'),
('chicken', 'Cordon Bleu', 'كوردن بلو'),
('chicken', 'Chicken Funji', 'تشيكن فونجي'),
('chicken', 'Chicken Piccata', 'بيكاتا فراخ'),
('chicken', 'Chilli Chicken', 'شيلي تشيكن'),
('chicken', 'Chicken Kijon', 'تشيكن كيجون'),
('chicken', 'Chicken Lemon', 'تشيكن ليمون'),
('chicken', 'Chicken Mushroom with Mozzarella', 'تشيكن مشروم و موزاريلا'),
('chicken', 'Chicken Crispy', 'تشيكن كرسبي'),
('chicken', 'Shish Tawook', 'شيش طاووق'),
('sea-food', 'Fish Fillet', 'سمك فيليه'),
('sea-food', 'Mussels 250 gm', 'بلح البحر 250 جم'),
('sea-food', 'Calamari 250 gm', 'كاليماري 250 جم'),
('sea-food', 'Shrimps 250 gm', 'جمبري 250 جم'),
('sea-food', 'Mix Seafood', 'مكس سي فود'),
('sea-food', 'Salmon Kebab', 'سلمون كباب'),
('sea-food', 'Grilled Salmon Steak', 'سلمون مشوي'),
('additions', 'Chicken', 'فراخ'),
('additions', 'Minces Meat', 'لحمة مفرومة'),
('additions', 'Sausage', 'سجق'),
('additions', 'Pastirami', 'بسطرمة'),
('additions', 'Salami', 'سلامي'),
('additions', 'Hotdog', 'هوت دوج'),
('additions', 'Tuna', 'تونة'),
('additions', 'Shrimps', 'جمبري'),
('additions', 'Calamari', 'كاليماري'),
('additions', 'Fish Fillet', 'سمك فيليه'),
('additions', 'Crab Stick', 'كابوريا اصابع'),
('additions', 'Caviar', 'كافيار'),
('additions', 'Olives', 'زيتون'),
('additions', 'Vegetables', 'خضروات'),
('additions', 'Mushroom', 'مشروم'),
('additions', 'jalapeno', 'هالابينو'),
('additions', 'Mozzarella Cheese', 'موزاريلا'),
('additions', 'Roumi cheese', 'رومي'),
('additions', 'Cheddar Cheese', 'شيدر'),
('additions', 'Blue Cheese', 'ريكفورد'),
('kids-menu', 'Dodo Meal', 'وجبه دودو'),
('additional-sides', 'White Rice', 'ارز ابيض'),
('additional-sides', 'White Rice with Vermicelli', 'ارز بالشعرية'),
('additional-sides', 'Brown Rice', 'ارز صيادية'),
('additional-sides', 'Basmati Rice', 'ارز بسمتي'),
('additional-sides', 'Mexican rice', 'ارز مكسيكي'),
('additional-sides', 'Sauteed Vegetables', 'خضار سوتيه'),
('additional-sides', 'Mashed Potatoes', 'بطاطس بوريه'),
('additional-sides', 'Red Sauce Pasta', 'باستا ريد صوص'),
('additional-sides', 'White Sauce Pasta', 'باستا وايت صوص'),
('fatta', 'Oriental Fattat', 'فته شرقي'),
('fatta', 'Fattet Chicken Shawarma', 'فته شاورما فراخ'),
('fatta', 'Fattet Meat shawarma', 'فته شاورما لحمه'),
('fatta', 'Fattet Shawarma Mix', 'فته شاورما مكس'),
('melted-cheese-bowls', 'Shish Tawook', 'شيش طاووق'),
('melted-cheese-bowls', 'Strips', 'استريبس'),
('melted-cheese-bowls', 'Zinger', 'زنجر'),
('melted-cheese-bowls', 'Cordon Bleu', 'كوردن بلو'),
('melted-cheese-bowls', 'Chicken Crispy', 'تشيكن كرسبي'),
('melted-cheese-bowls', 'Sausage', 'سجق'),
('melted-cheese-bowls', 'Kofta', 'كفتة'),
('melted-cheese-bowls', 'Pastirma', 'بسطرمة'),
('melted-cheese-bowls', 'Salami', 'سلامي'),
('melted-cheese-bowls', 'Hotdog', 'هوت دوج'),
('melted-cheese-bowls', 'Shrimps', 'جمبري'),
('melted-cheese-bowls', 'Calamari', 'كاليماري'),
('sandwiches', 'Chicken Crispy', 'تشيكن كرسبي'),
('sandwiches', 'Chicken Pane', 'تشيكن بانيه'),
('sandwiches', 'Shish Tawook Sandwich', 'شيش طاووق'),
('sandwiches', 'Zinger', 'زنجر'),
('sandwiches', 'Chicken Fajita Sandwich', 'فاهيتا فراخ'),
('sandwiches', 'Chicken Shawarma Sandwich', 'شاورما فراخ'),
('sandwiches', 'Cordon Bleu Sandwich', 'كوردن بلو'),
('sandwiches', 'Beef Fajita Sandwich', 'فاهيتا لحم'),
('sandwiches', 'Beef Shawarma Sandwich', 'شاورما لحم'),
('sandwiches', 'Kofta Sandwich', 'كفتة'),
('sandwiches', 'Classic Beef Burger', 'برجر لحم كلاسيك'),
('sandwiches', 'Cheese Burger', 'تشيز برجر'),
('sandwiches', 'Mushroom Burger', 'مشروم برجر'),
('sandwiches', 'Aquarium Burger', 'أكواريوم برجر'),
('sandwiches', 'Fried Shrimp Sandwich', 'جمبري مقلي'),
('sandwiches', 'Fried Fish Fillet Sandwich', 'سمك فيليه مقلي'),
('sandwiches', 'Fried Calamari Sandwich', 'كاليماري مقلي'),
('sandwiches', 'Tuna Sandwich', 'ساندوتش تونة'),
('sandwiches', 'Club Sandwich', 'كلوب ساندوتش'),
('desserts-waffles', 'Nutella Waffle', 'وافل نوتيلا'),
('desserts-waffles', 'Lotus Waffle', 'وافل لوتس'),
('desserts-waffles', 'Fruit Waffle', 'وافل فواكه'),
('desserts-waffles', 'Mix Sauce Waffle', 'وافل ميكس صوص'),
('desserts-waffles', 'Nutella Crepe', 'كريب نوتيلا'),
('desserts-waffles', 'Banana Nutella Crepe', 'كريب موز ونوتيلا'),
('desserts-waffles', 'Lotus Crepe', 'كريب لوتس'),
('desserts-waffles', 'Molten Cake', 'مولتن كيك'),
('desserts-waffles', 'Cheesecake', 'تشيز كيك'),
('desserts-waffles', 'Sweet Omelette / Pancake', 'أومليت حلو'),
('desserts-waffles', 'Om Ali with Nuts', 'أم علي بالمكسرات'),
('desserts-waffles', 'Ice Cream Scoop', 'بولة أيس كريم'),
('hot-drinks', 'Single Espresso', 'إسبرسو سينجل'),
('hot-drinks', 'Double Espresso', 'إسبرسو دبل'),
('hot-drinks', 'Americano', 'أمريكانو'),
('hot-drinks', 'Cappuccino', 'كابتشينو'),
('hot-drinks', 'Cafe Latte', 'لاتيه'),
('hot-drinks', 'Flat White', 'فلاد وايت'),
('hot-drinks', 'Hot Mocha', 'موكا ساخنة'),
('hot-drinks', 'Hot Chocolate', 'هوت شوكولاتة'),
('hot-drinks', 'Plain Sahlab', 'سحلب سادة'),
('hot-drinks', 'Sahlab with Nuts', 'سحلب بالمكسرات'),
('hot-drinks', 'Tea', 'شاي فتلة'),
('hot-drinks', 'Tea with Mint', 'شاي بالنعناع / أوراق الشاي'),
('hot-drinks', 'Herbal Tea', 'أعشاب طبيعية'),
('hot-drinks', 'Turkish Coffee Single', 'قهوة تركي سينجل'),
('hot-drinks', 'Turkish Coffee Double', 'قهوة تركي دبل'),
('hot-drinks', 'French Coffee', 'قهوة فرنساوي'),
('hot-drinks', 'Hazelnut Coffee', 'قهوة بندق'),
('cold-coffee-frappe', 'Iced Latte', 'آيس لاتيه'),
('cold-coffee-frappe', 'Iced Mocha', 'آيس موكا'),
('cold-coffee-frappe', 'Iced Americano', 'آيس أمريكانو'),
('cold-coffee-frappe', 'Vanilla Frappe', 'فرابيه فانيليا'),
('cold-coffee-frappe', 'Chocolate Frappe', 'فرابيه شوكولاتة'),
('cold-coffee-frappe', 'Caramel Frappe', 'فرابيه كراميل'),
('cold-coffee-frappe', 'Lotus Frappe', 'فرابيه لوتس'),
('juices-mojitos', 'Fresh Orange', 'عصير برتقال طازج'),
('juices-mojitos', 'Mango Juice', 'عصير مانجو'),
('juices-mojitos', 'Guava Juice', 'عصير جوافة'),
('juices-mojitos', 'Strawberry Juice', 'عصير فراولة'),
('juices-mojitos', 'Lemon Mint', 'عصير ليمون نعناع'),
('juices-mojitos', 'Banana Milkshake', 'عصير موز بالحليب'),
('juices-mojitos', 'Classic Mojito', 'موهيتو كلاسيك'),
('juices-mojitos', 'Blueberry Mojito', 'موهيتو بلوبيري'),
('juices-mojitos', 'Strawberry Mojito', 'موهيتو فراولة'),
('juices-mojitos', 'Special Cocktail', 'مكس العصائر الخاصة'),
('soft-drinks', 'Small Water', 'مياه معدنية صغيرة'),
('soft-drinks', 'Large Water', 'مياه معدنية كبيرة'),
('soft-drinks', 'Canned Soda', 'كانز كولا / سبرايت / فانتا'),
('soft-drinks', 'Energy Drink', 'مشروب طاقة'),
('soft-drinks', 'Schweppes', 'شويبس ذهبي / رومان'),
('soft-drinks', 'Birell / Fayrouz', 'بيريل / فيروز'),
('shisha', 'Traditional Shisha', 'شيشة قص / سلوم'),
('shisha', 'Two Apples Shisha', 'شيشة تفاحتين فاخر'),
('shisha', 'Flavored Shisha', 'شيشة خوخ / خلطات نكهات'),
('shisha', 'Aquarium Special Shisha', 'شيشة أكواريوم سبيشال'),
('shisha', 'Change Head Two Apples', 'تغيير حجر تفاحتين'),
('shisha', 'Change Head Flavor', 'تغيير حجر نكهة'),
('shisha', 'Hygienic Hose', 'لي طبي / هوز صحي'),
('smoothies-cocktails', 'Mango Smoothie', 'سموذي مانجو'),
('smoothies-cocktails', 'Strawberry Smoothie', 'سموذي فراولة'),
('smoothies-cocktails', 'Lemon Mint Smoothie', 'سموذي ليمون نعناع'),
('smoothies-cocktails', 'Watermelon Smoothie', 'سموذي بطيخ'),
('smoothies-cocktails', 'Blueberry Smoothie', 'سموذي بلوبيري'),
('smoothies-cocktails', 'Peach Smoothie', 'سموذي خوخ'),
('smoothies-cocktails', 'Bubble Gum Smoothie', 'سموذي بوبل جام'),
('smoothies-cocktails', 'Florida Cocktail', 'كوكتيل فلوريدا'),
('smoothies-cocktails', 'Aquarium Special Cocktail Mix', 'كوكتيل أكواريوم المتميز'),
('smoothies-cocktails', 'Pina Colada', 'بينا كولادا'),
('smoothies-cocktails', 'Sunrise Cocktail', 'صن رايز'),
('milkshakes', 'Vanilla Milkshake', 'ميلك شيك فانيليا'),
('milkshakes', 'Chocolate Milkshake', 'ميلك شيك شوكولاتة'),
('milkshakes', 'Strawberry Milkshake', 'ميلك شيك فراولة'),
('milkshakes', 'Mango Milkshake', 'ميلك شيك مانجو'),
('milkshakes', 'Oreo Milkshake', 'ميلك شيك أوريو'),
('milkshakes', 'Lotus Milkshake', 'ميلك شيك لوتس'),
('milkshakes', 'Nutella Milkshake', 'ميلك شيك نوتيلا'),
('milkshakes', 'Caramel Milkshake', 'ميلك شيك كراميل'),
('special-hot-coffee', 'Espresso Macchiato', 'إسبرسو مكياتو'),
('special-hot-coffee', 'Cortado', 'كورتادو'),
('special-hot-coffee', 'Caramel Coffee', 'قهوة بالكراميل'),
('special-hot-coffee', 'Vanilla Coffee', 'قهوة بالفانيليا'),
('special-hot-coffee', 'Arabic Coffee / Dallah', 'قهوة عربية'),
('special-hot-coffee', 'Hot Cider', 'هوت سيدار / تفاح بالسينامون'),
('special-hot-coffee', 'Warm Milk with Honey', 'حليب دافئ بالعسل')
) as m(category_slug,name,name_ar) join public.categories c2 on c2.slug=m.category_slug where c2.id=p.category_id and m.name=p.name and m.name_ar=p.name_ar);

insert into public.website_content (key,value) values ('menu_vat_notice', '{"en":"Prices shown include 14% VAT.","ar":"الأسعار الموضحة تشمل 14% ضريبة القيمة المضافة."}'::jsonb) on conflict (key) do update set value=excluded.value;
