-- Aquarium Cafe: Web Push subscriptions + RPC
create table if not exists public.notification_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  role text not null check (role in ('waiter','customer')),
  order_id uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notification_subscriptions_role_idx
  on public.notification_subscriptions(role);
create index if not exists notification_subscriptions_order_idx
  on public.notification_subscriptions(order_id);

alter table public.notification_subscriptions enable row level security;

create or replace function public.register_push_subscription(p jsonb)
returns json
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint;
begin
  if coalesce(p->>'endpoint','') = '' or coalesce(p->>'p256dh','') = '' or coalesce(p->>'auth','') = '' then
    raise exception 'Invalid push subscription.';
  end if;
  if p->>'role' not in ('waiter','customer') then
    raise exception 'Invalid push role.';
  end if;

  insert into public.notification_subscriptions(endpoint,p256dh,auth,role,order_id,updated_at)
  values (
    p->>'endpoint',
    p->>'p256dh',
    p->>'auth',
    p->>'role',
    nullif(p->>'order_id','')::uuid,
    now()
  )
  on conflict(endpoint) do update set
    p256dh=excluded.p256dh,
    auth=excluded.auth,
    role=excluded.role,
    order_id=excluded.order_id,
    updated_at=now()
  returning id into v_id;

  return json_build_object('id',v_id);
end;
$$;

revoke all on function public.register_push_subscription(jsonb) from public;
grant execute on function public.register_push_subscription(jsonb) to anon, authenticated;
